
import datetime
import steps.model as smodel
import math
import sys
import numpy 
import numpy as np
from numpy import mean
import steps.solver as swmdirect
import steps.geom as swm
import steps.rng as srng
from pylab import*
import os
import pickle

#calc_3_3 = 0
#calc_3_1 = 0
calc_3_4 = 0
#totPKC = 0
DT = 0.05 # time step
INT = 700 # final time (s) simulated
NITER = 1 # number of runs used to calculate the mean
tinit = 5 # initial time that will be discharged. The initial 10 minutes of all simulations should be discharged to allow the model to reach equilibrium.

# Avogadro constant
Na = 6.02214129e23
Kin = input("Calcium Kinase input")
type (Kin)
########################################################################

# Ca2+ pulse. IMPORTANT: the duration and amplitude of the pulse should be checked directly in the Ca2+ concentration
# The changes in [Ca2+] generated by the pulses are highly stochastic
# altering max_molar alters the maximum molar concentration per second injection (M/s) 
# cntr defines the time the pulse is at maximum (s)
# FW100M defines the full-width 100th maximum of the Gaussian (s)

#def gaussian_ica(t,max_molar=100.0e-6/0.05,cntr=1000.0,FW100M=120):
    #c = FW100M/(2*math.sqrt(2*math.log(100)))
    #return max_molar*np.exp(-(((t-cntr)**2)/(2*c**2)))

######################################################################## 

def gen_model(): 
    mdl=smodel.Model() 
    
    Ca = smodel.Spec('Ca', mdl)
    #CBf = smodel.Spec('CBf',mdl)
    #CaCBf = smodel.Spec('CaCBf',mdl)
    #Ca2CBf = smodel.Spec('Ca2CBf',mdl)
    PP2A = smodel.Spec('PP2A', mdl)                        
    PP1 = smodel.Spec('PP1', mdl)
    

    CaM = smodel.Spec('CaM',mdl)
    CaM1Ca = smodel.Spec('CaM1Ca',mdl)
    CaM2Ca = smodel.Spec('CaM2Ca',mdl)
    CaM3Ca = smodel.Spec('CaM3Ca',mdl)
    CaN = smodel.Spec('CaN',mdl)
    CaM3CaCaN = smodel.Spec('CaM3CaCaN',mdl)
    CaMKII = smodel.Spec('CaMKII',mdl)
    CaM3Ca_CaMKII = smodel.Spec('CaM3Ca_CaMKII',mdl)
    CaM3Ca_pT286287 = smodel.Spec('CaM3Ca_pT286287',mdl)
    pT286287 = smodel.Spec('pT286287',mdl)
    pT286287_pT308306 = smodel.Spec('pT286287_pT308306',mdl)
    pT308306 = smodel.Spec('pT308306',mdl)

    GC = smodel.Spec('GC',mdl)
    NO = smodel.Spec('NO',mdl)
    GC_NO = smodel.Spec('GC_NO',mdl)
    GTP = smodel.Spec('GTP',mdl)
    GTP_GC_NO = smodel.Spec('GTP_GC_NO',mdl)
    cGMP = smodel.Spec('cGMP',mdl)
    GMP = smodel.Spec('GMP',mdl)
    PDE1 = smodel.Spec('PDE1',mdl)
    pPDE1 = smodel.Spec('pPDE1',mdl)
    PDE5 = smodel.Spec('PDE5',mdl)
    PDE5_cGMP = smodel.Spec('PDE5_cGMP',mdl)
    PKG = smodel.Spec('PKG',mdl)
    PKG_cGMP = smodel.Spec('PKG_cGMP',mdl)
    PP2A_pGsub = smodel.Spec('PP2A_pGsub',mdl)
    pG = smodel.Spec('pG',mdl)
    G_sub = smodel.Spec('G_sub',mdl)

    CaM3Ca_pT286287_PP1 = smodel.Spec('CaM3Ca_pT286287_PP1',mdl)
    CaM3Ca_pT286287_PP2A = smodel.Spec('CaM3Ca_pT286287_PP2A',mdl)
    pT286287_pT308306_PP1 = smodel.Spec('pT286287_pT308306_PP1',mdl)
    pT286287_pT308306_PP2A = smodel.Spec('pT286287_pT308306_PP2A',mdl)
    pT286287_PP1 = smodel.Spec('pT286287_PP1',mdl)
    pT286287_PP2A = smodel.Spec('pT286287_PP2A',mdl)
    pT286287_pT308306_PP1_2 = smodel.Spec('pT286287_pT308306_PP1_2',mdl)
    pT286287_pT308306_PP2A_2 = smodel.Spec('pT286287_pT308306_PP2A_2',mdl)
    pT308306_PP1 = smodel.Spec('pT308306_PP1',mdl)
    pT308306_PP2A = smodel.Spec('pT308306_PP2A',mdl)
    cGMP_CaM3Ca_pPDE1 = smodel.Spec('cGMP_CaM3Ca_pPDE1',mdl)
    cGMP_CaM3Ca_PDE1 = smodel.Spec('cGMP_CaM3Ca_PDE1',mdl)
    cGMP_PDE1 = smodel.Spec('cGMP_PDE1',mdl)
    cGMP_PDE5 = smodel.Spec('cGMP_PDE5',mdl)
    cGMP_pPDE1 = smodel.Spec('cGMP_pPDE1',mdl)
    PDE1_CaMKII = smodel.Spec('PDE1_CaMKII',mdl)
    pPDE1_CaN = smodel.Spec('pPDE1_CaN',mdl)
    CaM3Ca_PDE1_CaMKII = smodel.Spec('CaM3Ca_PDE1_CaMKII',mdl)
    CaM3Ca_pPDE1_CaN = smodel.Spec('CaM3Ca_pPDE1_CaN',mdl)
    pG_PP2A = smodel.Spec('pG_PP2A',mdl)
    pG_CaN = smodel.Spec('pG_CaN',mdl)
    G_sub_PKG = smodel.Spec('G_sub_PKG',mdl)
    CaM3Ca_PDE1 = smodel.Spec('CaM3Ca_PDE1',mdl)
    CaM3Ca_pPDE1 = smodel.Spec('CaM3Ca_pPDE1',mdl)

    PP1_pDARPP32 = smodel.Spec('PP1_pDARPP32',mdl)
    PP1_DARPP32 = smodel.Spec('PP1_DARPP32',mdl)
    DARPP32 = smodel.Spec('DARPP32',mdl)
    pDARPP32 = smodel.Spec('pDARPP32',mdl)
    R2C2_PKA = smodel.Spec('R2C2_PKA',mdl)
    cAMP_R2C2 = smodel.Spec('cAMP_R2C2',mdl)
    cAMP2_bb_R2C2 = smodel.Spec('cAMP2_bb_R2C2',mdl)
    cAMP2_ab_R2C2 = smodel.Spec('cAMP2_ab_R2C2',mdl)
    cAMP2_ab_R2C = smodel.Spec('cAMP2_ab_R2C',mdl)
    cAMP3_R2C2 = smodel.Spec('cAMP3_R2C2',mdl)
    cAMP3_R2C = smodel.Spec('cAMP3_R2C',mdl)
    cAMP4_R2C2 = smodel.Spec('cAMP4_R2C2',mdl)
    cAMP4_R2C = smodel.Spec('cAMP4_R2C',mdl)
    cAMP4_R2 = smodel.Spec('cAMP4_R2',mdl)
    C_actPKA = smodel.Spec('C_actPKA',mdl)
    cAMP = smodel.Spec('cAMP',mdl)
    AMP = smodel.Spec('AMP',mdl)
    PDE4 = smodel.Spec('PDE4',mdl)
    cAMP_pPDE1 = smodel.Spec('cAMP_pPDE1',mdl)
    cAMP_PDE1 = smodel.Spec('cAMP_PDE1',mdl)
    cAMP_CaM3Ca_PDE1 = smodel.Spec('cAMP_CaM3Ca_PDE1',mdl)
    cAMP_CaM3Ca_pPDE1 = smodel.Spec('cAMP_CaM3Ca_pPDE1',mdl)
    cAMP_PDE4 = smodel.Spec('cAMP_PDE4',mdl)

    PP1_pDARPP32_PP2A = smodel.Spec('PP1_pDARPP32_PP2A',mdl)
    PP1_pDARPP32_CaN = smodel.Spec('PP1_pDARPP32_CaN',mdl)
    PP1_DARPP32_C_actPKA = smodel.Spec('PP1_DARPP32_C_actPKA',mdl)
    pDARPP32_PP2A = smodel.Spec('pDARPP32_PP2A',mdl)
    pDARPP32_CaN = smodel.Spec('pDARPP32_CaN',mdl)
    DARPP32_C_actPKA = smodel.Spec('DARPP32_C_actPKA',mdl)
    
    AA = smodel.Spec('AA',mdl)
    PKC = smodel.Spec('PKC',mdl)
    PKCAA = smodel.Spec('PKCAA',mdl)
    DAG = smodel.Spec('DAG',mdl)
    PKCDAGAA = smodel.Spec('PKCDAGAA',mdl)
    PKCCaDAGAA = smodel.Spec('PKCCaDAGAA',mdl)
    PKCCaDAG = smodel.Spec('PKCCaDAG',mdl)
    PKCCaAA = smodel.Spec('PKCCaAA',mdl)
    PKCCacyto = smodel.Spec('PKCCacyto',mdl)
    PKCCamemb = smodel.Spec('PKCCamemb',mdl)

    Raf = smodel.Spec('Raf',mdl)
    actRaf = smodel.Spec('actRaf',mdl)
    MAPKK = smodel.Spec('MAPKK',mdl)
    MAPKK_ser = smodel.Spec('MAPKK_ser',mdl)
    act_MAPKK = smodel.Spec('act_MAPKK',mdl)
    MAPK = smodel.Spec('MAPK',mdl)
    MAPK_tyr = smodel.Spec('MAPK_tyr',mdl)
    act_MAPK = smodel.Spec('act_MAPK',mdl)
    MKP_1 = smodel.Spec('MKP_1',mdl)
    PLA2_MAPK = smodel.Spec('PLA2_MAPK',mdl)

    APC = smodel.Spec('APC',mdl)
    PLA2_PIP2 = smodel.Spec('PLA2_PIP2',mdl)
    pPLA2_Ca = smodel.Spec('pPLA2_Ca',mdl)
    PLA2_Ca = smodel.Spec('PLA2_Ca',mdl)
    PLA2 = smodel.Spec('PLA2',mdl)
    pPLA2 = smodel.Spec('pPLA2',mdl)
    PLA2_PIP2_Ca = smodel.Spec('PLA2_PIP2_Ca',mdl)
    DAG_PLA2_Ca = smodel.Spec('DAG_PLA2_Ca',mdl)
    PLA_PLA2 = smodel.Spec('PLA_PLA2',mdl)
    PLA_PLA2_Ca = smodel.Spec('PLA_PLA2_Ca',mdl)
    PIP2 = smodel.Spec('PIP2',mdl)
    AA_deg = smodel.Spec('AA_deg',mdl)
    APC_PLA2_PIP2 = smodel.Spec('APC_PLA2_PIP2',mdl)
    APC_pPLA2_Ca = smodel.Spec('APC_pPLA2_Ca',mdl)
    APC_PLA2_Ca = smodel.Spec('APC_PLA2_Ca',mdl)
    APC_pPLA2 = smodel.Spec('APC_pPLA2',mdl)
    APC_PLA2_PIP2_Ca = smodel.Spec('APC_PLA2_PIP2_Ca',mdl)
    APC_DAG_PLA2_Ca = smodel.Spec('APC_DAG_PLA2_Ca',mdl)

    Raf_PKC = smodel.Spec('Raf_PKC',mdl)
    act_Raf_PP2A = smodel.Spec('act_Raf_PP2A',mdl)
    MAPKK_Raf = smodel.Spec('MAPKK_Raf',mdl)
    MAPKK_ser_Raf = smodel.Spec('MAPKK_ser_Raf',mdl)
    act_MAPKK_PP2A = smodel.Spec('act_MAPKK_PP2A',mdl)
    MAPKK_ser_PP2A = smodel.Spec('MAPKK_ser_PP2A',mdl)
    MAPK_MAPKK = smodel.Spec('MAPK_MAPKK',mdl)
    MAPK_tyr_MAPKK = smodel.Spec('MAPK_tyr_MAPKK',mdl)
    act_MAPK_MKP_1 = smodel.Spec('act_MAPK_MKP_1',mdl)
    MAPK_tyr_MKP_1 = smodel.Spec('MAPK_tyr_MKP_1',mdl)

   
    PLA2_Ca_DAG = smodel.Spec('PLA2_Ca_DAG',mdl)
    PLA2_Ca_PIP2 = smodel.Spec('PLA2_Ca_PIP2',mdl)
    act_Raf = smodel.Spec('act_Raf',mdl)
    act_MAPKK_ser = smodel.Spec('act_MAPKK_ser',mdl)
    PKC_AA = smodel.Spec('PKC_AA',mdl)
    PKC_Ca_AA = smodel.Spec('PKC_Ca_AA',mdl)
    PKC_DAG_AA = smodel.Spec('PKC_DAG_AA',mdl)
    PKC_Ca_DAG_AA = smodel.Spec('PKC_Ca_DAG_AA',mdl)
    PKC_Ca_DAG = smodel.Spec('PKC_Ca_DAG',mdl)

    AMPAR = smodel.Spec('AMPAR',mdl)
    pAMPAR = smodel.Spec('pAMPAR',mdl)
    
    totPKC_AMPAR = smodel.Spec('totPKC_AMPAR',mdl)
    PP2A_pAMPAR = smodel.Spec('PP2A_pAMPAR',mdl)
    GABAaR = smodel.Spec('GABAaR',mdl)
    pGABAaR = smodel.Spec('pGABAaR',mdl)
    GABAaR_CaMKII = smodel.Spec('GABAaR_CaMKII',mdl)
    pGABAaR_PP1 = smodel.Spec('pGABAaR_PP1',mdl)

    IP3 = smodel.Spec('IP3',mdl)
    PLC_Gq = smodel.Spec('PLC_Gq',mdl)
    PLC = smodel.Spec('PLC',mdl)
    GTPaq = smodel.Spec('GTPaq',mdl)
    GDPaq = smodel.Spec('GDPaq',mdl)
    GTPaqbg = smodel.Spec('GTPaqbg',mdl)
    GDPaqbg = smodel.Spec('GDPaqbg',mdl)
    GTPaibg = smodel.Spec('GTPaibg',mdl)
    GDPaibg = smodel.Spec('GDPaibg',mdl)
    GTPas = smodel.Spec('GTPas',mdl)
    GDPas = smodel.Spec('GDPas',mdl)
    GTPasbg = smodel.Spec('GTPasbg',mdl)
    GDPasbg = smodel.Spec('GDPasbg',mdl)
    bg = smodel.Spec('bg',mdl)
    Glu = smodel.Spec('Glu',mdl)
    mGluR1 = smodel.Spec('mGluR1',mdl)
    Glu_mGluR1 = smodel.Spec('Glu_mGluR1',mdl)
    mGluR1_GDPaqbg = smodel.Spec('mGluR1_GDPaqbg',mdl)
    mGluR1_GDPasbg = smodel.Spec('mGluR1_GDPasbg',mdl)
    Glu_mGluR1_GDPaqbg = smodel.Spec('Glu_mGluR1_GDPaqbg',mdl)
    Glu_mGluR1_GDPasbg = smodel.Spec('Glu_mGluR1_GDPasbg',mdl) 
    GABA = smodel.Spec('GABA',mdl)
    GABAbR = smodel.Spec('GABAbR',mdl)
    GABA_GABAbR = smodel.Spec('GABA_GABAbR',mdl)
    GABAbR_GDPaibg = smodel.Spec('GABAbR_GDPaibg',mdl)
    GABA_GABAbR_GDPaibg = smodel.Spec('GABA_GABAbR_GDPaibg',mdl)
    actGi = smodel.Spec('actGi',mdl)
    Gi = smodel.Spec('Gi',mdl)
    GTPai = smodel.Spec('GTPai',mdl)
    GDPai = smodel.Spec('GDPai',mdl)
    AC = smodel.Spec('AC',mdl)
    inac_AC = smodel.Spec('inac_AC',mdl)
    AC_GDPai = smodel.Spec('AC_GDPai',mdl)
    actAC = smodel.Spec('actAC',mdl)
    AC_GDPas = smodel.Spec('AC_GDPas',mdl)
    ATP = smodel.Spec('ATP',mdl)
    ATP_actAC = smodel.Spec('ATP_actAC',mdl)
    ATP_AC_GDPas = smodel.Spec('ATP_AC_GDPas',mdl) 
    deg = smodel.Spec('deg',mdl)
    PIP2_PLC_Gq = smodel.Spec('PIP2_PLC_Gq',mdl)
    pG_CaM3CaCaN = smodel.Spec('pG_CaM3CaCaN',mdl)
    act_PDE5 = smodel.Spec('act_PDE5',mdl)
    calc_3_1 = smodel.Spec('calc_3_1',mdl)
    calc_3_3 = smodel.Spec('calc_3_3',mdl)
    #calc_3_4 = smodel.Spec('calc_3_4',mdl)
    totPKC = smodel.Spec('totPKC',mdl)

    totbasGTP = smodel.Spec('totbasGTP',mdl)


    vsys = smodel.Volsys('vsys', mdl)
    

    ########################################################################
    ########################################################################
    
    #Reactions    
    #Ca influx (Ca = calcium)
    #CainfluxR = smodel.Reac('Cainflux', vsys, rhs=[Ca])
    #reaction constant for zero-order reaction units M/s in STEPS 1.2 and above
    #CainfluxR.kcst = 0.0 
    
    #CBf + Ca <-> CaCBf + Ca <-> Ca2CBf, CBf - medium affinity site
    #Reac27 = smodel.Reac('Reac27', vsys, lhs = [CBf, Ca], rhs = [CaCBf])
    #Reac27.kcst = 43.5e6 
    #Reac28 = smodel.Reac('Reac28', vsys, lhs = [CaCBf], rhs = [CBf, Ca])
    #Reac28.kcst = 35.8
    #Reac29 = smodel.Reac('Reac29', vsys, lhs = [CaCBf, Ca], rhs = [Ca2CBf])
    #Reac29.kcst = 43.5e6 
    #Reac30 = smodel.Reac('Reac30', vsys, lhs = [Ca2CBf], rhs = [CaCBf, Ca])
    #Reac30.kcst = 35.8

    # CaM + Ca <-> CaM1Ca <-> CaM2Ca <-> CaM3Ca 
    Reac208 = smodel.Reac('Reac208', vsys, lhs = [CaM, Ca], rhs = [CaM1Ca])
    Reac208.kcst = 4e6
    Reac209 = smodel.Reac('Reac209', vsys, lhs = [CaM1Ca], rhs = [CaM, Ca])
    Reac209.kcst = 100
    Reac210 = smodel.Reac('Reac210', vsys, lhs = [CaM1Ca,Ca], rhs = [CaM2Ca])
    Reac210.kcst = 40e6
    Reac211 = smodel.Reac('Reac211', vsys, lhs = [CaM2Ca], rhs = [CaM1Ca, Ca])
    Reac211.kcst = 640
    Reac212 = smodel.Reac('Reac212', vsys, lhs = [CaM2Ca, Ca], rhs = [CaM3Ca])
    Reac212.kcst = 40e6
    Reac213 = smodel.Reac('Reac213', vsys, lhs = [CaM3Ca], rhs = [CaM2Ca, Ca])
    Reac213.kcst = 700
    
    # CaN + CaM3Ca <-> CaM3CaCaN
    Reac214 = smodel.Reac('Reac214', vsys, lhs = [CaN, CaM3Ca] , rhs = [CaM3CaCaN])
    Reac214.kcst = 400e6
    Reac215 = smodel.Reac('Reac215', vsys, lhs = [CaM3CaCaN], rhs = [CaN,CaM3Ca])
    Reac215.kcst = 3 

    # CaMKII + CaM3Ca <-> CaM3Ca_CaMKII
    Reac216 = smodel.Reac('Reac216', vsys, lhs = [CaMKII, CaM3Ca], rhs = [CaM3Ca_CaMKII])
    Reac216.kcst = 400e6
    Reac217 = smodel.Reac('Reac217', vsys, lhs = [CaM3Ca_CaMKII], rhs = [CaMKII, CaM3Ca])
    Reac217.kcst = 8

    # CaM3Ca_CaMKII + calc_3_3 -> CaM3Ca_pT286287
    Reac218 = smodel.Reac('Reac218', vsys, lhs = [CaM3Ca_CaMKII,calc_3_3], rhs = [CaM3Ca_pT286287])
    Reac218.kcst = 11e6

    # CaM3Ca_pT286287 + PP1 <-> CaM3Ca_pT286287_PP1 -> CaM3Ca_CaMKII + PP1
    Reac219 = smodel.Reac('Reac219', vsys, lhs = [CaM3Ca_pT286287 , PP1], rhs = [CaM3Ca_pT286287_PP1])
    Reac219.kcst = 3.3333e6
    Reac220 = smodel.Reac('Reac220', vsys, lhs = [CaM3Ca_pT286287_PP1], rhs = [CaM3Ca_pT286287, PP1] )
    Reac220.kcst = 8
    Reac221 = smodel.Reac('Reac221', vsys, lhs = [CaM3Ca_pT286287_PP1], rhs = [CaM3Ca_CaMKII,PP1])
    Reac221.kcst = 2

    # CaM3Ca_pT286287 + PP2A <-> CaM3Ca_pT286287_PP2A -> CaM3Ca_CaMKII + PP2A
    Reac222 = smodel.Reac('Reac222', vsys, lhs = [CaM3Ca_pT286287 , PP2A], rhs = [CaM3Ca_pT286287_PP2A])
    Reac222.kcst = 0.2e6
    Reac223 = smodel.Reac('Reac223', vsys, lhs = [CaM3Ca_pT286287_PP2A], rhs = [CaM3Ca_pT286287, PP2A] )
    Reac223.kcst = 0.8
    Reac224 = smodel.Reac('Reac224', vsys, lhs = [CaM3Ca_pT286287_PP2A], rhs = [CaM3Ca_CaMKII, PP2A])
    Reac224.kcst = 0.2

    # pT286287 + CaM3Ca <-> CaM3Ca_pT286287
    Reac225 = smodel.Reac('Reac225', vsys, lhs = [pT286287, CaM3Ca], rhs = [CaM3Ca_pT286287])
    Reac225.kcst = 400e6
    Reac226 = smodel.Reac('Reac226', vsys, lhs = [CaM3Ca_pT286287], rhs = [pT286287, CaM3Ca])
    Reac226.kcst = 0.24

    # pT286287 -> pT286287_pT308306
    Reac227 = smodel.Reac('Reac227', vsys, lhs = [pT286287,calc_3_3], rhs = [pT286287_pT308306])
    Reac227.kcst = 0.5e6

    # pT286287_pT308306 + PP1 <-> pT286287_pT308306_PP1 -> pT286287 + PP1 
    Reac228 = smodel.Reac('Reac228', vsys, lhs = [pT286287_pT308306, PP1], rhs = [pT286287_pT308306_PP1])
    Reac228.kcst = 3.3333e6
    Reac229 = smodel.Reac('Reac229', vsys, lhs = [pT286287_pT308306_PP1], rhs =[pT286287_pT308306, PP1])
    Reac229.kcst = 8
    Reac230 = smodel.Reac('Reac230', vsys, lhs = [pT286287_pT308306_PP1], rhs = [pT286287, PP1])
    Reac230.kcst = 2

    # pT286287_pT308306 + PP2A <-> pT286287_pT308306_PP2A -> pT286287 + PP2A
    Reac231 = smodel.Reac('Reac231', vsys, lhs = [pT286287_pT308306, PP2A], rhs = [pT286287_pT308306_PP2A])
    Reac231.kcst = 0.2e6
    Reac232 = smodel.Reac('Reac232', vsys, lhs = [pT286287_pT308306_PP2A], rhs =[pT286287_pT308306, PP2A])
    Reac232.kcst = 0.8
    Reac233 = smodel.Reac('Reac233', vsys, lhs = [pT286287_pT308306_PP2A], rhs = [pT286287, PP2A])
    Reac233.kcst =  0.2

    # pT286287 + PP1 <-> pT286287_PP1 -> CaMKII + PP1
    Reac234 = smodel.Reac('Reac234', vsys, lhs = [pT286287, PP1], rhs = [pT286287_PP1])
    Reac234.kcst = 3.3333e6
    Reac235 = smodel.Reac('Reac235', vsys, lhs = [pT286287_PP1], rhs =[pT286287, PP1])
    Reac235.kcst = 8
    Reac236 = smodel.Reac('Reac236', vsys, lhs = [pT286287_PP1], rhs = [CaMKII, PP1])
    Reac236.kcst = 2

    # pT286287 + PP2A <-> pT286287_PP2A -> CaMKII + PP2A
    Reac237 = smodel.Reac('Reac237', vsys, lhs = [pT286287, PP2A], rhs = [pT286287_PP2A])
    Reac237.kcst = 0.2e6
    Reac238 = smodel.Reac('Reac238', vsys, lhs = [pT286287_PP2A], rhs =[pT286287, PP2A])
    Reac238.kcst = 0.8
    Reac239 = smodel.Reac('Reac239', vsys, lhs = [pT286287_PP2A], rhs = [CaMKII, PP2A])
    Reac239.kcst = 0.2

    # pT286287_pT308306 + PP1 <-> pT286287_pT308306_PP1_2 -> pT308306 + PP1
    Reac240 = smodel.Reac('Reac240', vsys, lhs = [pT286287_pT308306, PP1], rhs = [pT286287_pT308306_PP1_2])
    Reac240.kcst = 3.3333e6
    Reac241 = smodel.Reac('Reac241', vsys, lhs = [pT286287_pT308306_PP1_2], rhs =[pT286287_pT308306, PP1])
    Reac241.kcst = 8
    Reac242 = smodel.Reac('Reac242', vsys, lhs = [pT286287_pT308306_PP1_2], rhs = [pT308306, PP1])
    Reac242.kcst = 2

    # pT286287_pT308306 + PP2A <-> pT286287_pT308306_PP2A_2 -> pT308306 + PP2A
    Reac243 = smodel.Reac('Reac243', vsys, lhs = [pT286287_pT308306, PP2A], rhs = [pT286287_pT308306_PP2A_2])
    Reac243.kcst = 0.2e6
    Reac244 = smodel.Reac('Reac244', vsys, lhs = [pT286287_pT308306_PP2A_2], rhs =[pT286287_pT308306, PP2A])
    Reac244.kcst = 0.8
    Reac245 = smodel.Reac('Reac245', vsys, lhs = [pT286287_pT308306_PP2A_2], rhs = [pT308306, PP2A])
    Reac245.kcst = 0.2

 
    # pT308306 + PP1 <-> pT308306_PP1 -> CaMKII + PP1
    Reac246 = smodel.Reac('Reac246', vsys, lhs = [pT308306, PP1], rhs = [pT308306_PP1])
    Reac246.kcst = 3.3333e6
    Reac247 = smodel.Reac('Reac247', vsys, lhs = [pT308306_PP1], rhs =[pT308306, PP1])
    Reac247.kcst = 8
    Reac248 = smodel.Reac('Reac248', vsys, lhs = [pT308306_PP1], rhs = [CaMKII, PP1])
    Reac248.kcst = 2

    # pT308306 + PP2A <-> pT308306_PP2A -> CaMKII + PP2A
    Reac249 = smodel.Reac('Reac249', vsys, lhs = [pT308306, PP2A], rhs = [pT308306_PP2A])
    Reac249.kcst = 0.2e6
    Reac250 = smodel.Reac('Reac250', vsys, lhs = [pT308306_PP2A], rhs =[pT308306, PP2A])
    Reac250.kcst = 0.8
    Reac251 = smodel.Reac('Reac251', vsys, lhs = [pT308306_PP2A], rhs = [CaMKII, PP2A])
    Reac251.kcst = 0.2

    # GC + NO <-> GC_NO
    Reac252 = smodel.Reac('Reac252', vsys, lhs = [GC,NO], rhs = [GC_NO])
    Reac252.kcst = 1e6
    Reac253 = smodel.Reac('Reac253', vsys, lhs = [GC_NO], rhs = [GC,NO])
    Reac253.kcst = 0.01

    #GC_NO + GTP <-> GTP_GC_NO
    Reac254 = smodel.Reac('Reac254', vsys, lhs =[GC_NO, GTP], rhs = [GTP_GC_NO])
    Reac254.kcst = 0.735e6
    Reac255 = smodel.Reac('Reac255', vsys, lhs =[GTP_GC_NO], rhs = [GC_NO, GTP])
    Reac255.kcst = 29.4

    #GTP_GC_NO -> cGMP + GC_NO
    Reac256 = smodel.Reac('Reac256', vsys, lhs = [GTP_GC_NO], rhs = [cGMP,GC_NO])
    Reac256.kcst = 7.35

    #GC_NO -> GC
    Reac257 = smodel.Reac('Reac257', vsys, lhs = [GC_NO], rhs = [GC]) 
    Reac257.kcst = 0.673
    

    #cGMP + CaM3Ca_pPDE1 <-> cGMP_CaM3Ca_pPDE1 -> GMP + CaM3Ca_pPDE1
    Reac258 = smodel.Reac('Reac258', vsys, lhs = [cGMP,CaM3Ca_pPDE1], rhs = [cGMP_CaM3Ca_pPDE1])
    Reac258.kcst = 37.5e6
    Reac259 = smodel.Reac('Reac259', vsys, lhs = [cGMP_CaM3Ca_pPDE1], rhs = [cGMP,CaM3Ca_pPDE1])
    Reac259.kcst = 60
    Reac260 = smodel.Reac('Reac260', vsys, lhs = [cGMP_CaM3Ca_pPDE1], rhs = [GMP, CaM3Ca_pPDE1])
    Reac260.kcst = 15

    #cGMP + CaM3Ca_PDE1 <-> cGMP_CaM3Ca_PDE1 -> GMP + CaM3Ca_PDE1
    Reac261 = smodel.Reac('Reac261', vsys, lhs = [cGMP,CaM3Ca_PDE1], rhs = [cGMP_CaM3Ca_PDE1])
    Reac261.kcst = 37.5e6
    Reac262 = smodel.Reac('Reac262', vsys, lhs = [cGMP_CaM3Ca_PDE1], rhs = [cGMP,CaM3Ca_PDE1])
    Reac262.kcst = 60
    Reac263 = smodel.Reac('Reac263', vsys, lhs = [cGMP_CaM3Ca_PDE1], rhs = [GMP, CaM3Ca_PDE1])
    Reac263.kcst = 15 

    #cGMP + pPDE1 <-> cGMP_pPDE1 -> GMP + pPDE1
    Reac264 = smodel.Reac('Reac264', vsys, lhs = [cGMP,pPDE1], rhs = [cGMP_pPDE1])
    Reac264.kcst = 0.25e6
    Reac265 = smodel.Reac('Reac265', vsys, lhs = [cGMP_pPDE1], rhs = [cGMP,pPDE1])
    Reac265.kcst = 0.4 
    Reac266 = smodel.Reac('Reac266', vsys, lhs = [cGMP_pPDE1], rhs = [GMP, pPDE1])
    Reac266.kcst = 0.1

    #cGMP + PDE1 <-> cGMP_PDE1 -> GMP + PDE1 
    Reac267 = smodel.Reac('Reac267', vsys, lhs = [cGMP,PDE1], rhs = [cGMP_PDE1])
    Reac267.kcst = 0.25e6
    Reac268 = smodel.Reac('Reac268', vsys, lhs = [cGMP_PDE1], rhs = [cGMP,PDE1])
    Reac268.kcst = 0.4
    Reac269 = smodel.Reac('Reac269', vsys, lhs = [cGMP_PDE1], rhs = [GMP, PDE1])
    Reac269.kcst = 0.1

    #cGMP + PDE5 <-> cGMP_PDE5 -> GMP + PDE5 
    Reac270 = smodel.Reac('Reac270', vsys, lhs = [cGMP,act_PDE5], rhs = [cGMP_PDE5])
    Reac270.kcst = 7.5e6
    Reac271 = smodel.Reac('Reac271', vsys, lhs = [cGMP_PDE5], rhs = [cGMP,act_PDE5])
    Reac271.kcst = 12 
    Reac272 = smodel.Reac('Reac272', vsys, lhs = [cGMP_PDE5], rhs = [GMP, act_PDE5])
    Reac272.kcst = 3

    
    #pPDE1 -> PDE1 
    Reac273 = smodel.Reac('Reac273', vsys, lhs = [pPDE1], rhs = [PDE1])
    Reac273.kcst = 0.2

    #CaM3Ca_pPDE1 -> CaM3Ca_PDE1 
    Reac274 = smodel.Reac('Reac274', vsys, lhs = [CaM3Ca_pPDE1], rhs = [CaM3Ca_PDE1])
    Reac274.kcst = 0.2

    #PDE1  <-> PDE1_CaMKII -> pPDE1 
    Reac275 = smodel.Reac('Reac275', vsys, lhs = [PDE1,calc_3_1], rhs = [PDE1_CaMKII])
    Reac275.kcst = 0.90909090e6
    Reac276 = smodel.Reac('Reac276', vsys, lhs = [PDE1_CaMKII], rhs = [PDE1])
    Reac276.kcst = 8 
    Reac277 = smodel.Reac('Reac277', vsys, lhs = [PDE1_CaMKII], rhs = [pPDE1])
    Reac277.kcst = 2 

    #pPDE1 + CaN <-> pPDE1_CaN -> PDE1 + CaN
    Reac278 = smodel.Reac('Reac278', vsys, lhs = [pPDE1, CaM3CaCaN], rhs = [pPDE1_CaN])
    Reac278.kcst = 1.25e6
    Reac279 = smodel.Reac('Reac279', vsys, lhs = [pPDE1_CaN], rhs = [pPDE1, CaM3CaCaN])
    Reac279.kcst = 2 
    Reac280 = smodel.Reac('Reac280', vsys, lhs = [pPDE1_CaN], rhs = [PDE1, CaM3CaCaN])
    Reac280.kcst = 0.5 

    #CaM3Ca_PDE1 <-> CaM3Ca_PDE1_CaMKII -> CaM3Ca_pPDE1 
    Reac281 = smodel.Reac('Reac281', vsys, lhs = [CaM3Ca_PDE1,calc_3_1], rhs = [CaM3Ca_PDE1_CaMKII])
    Reac281.kcst = 0.90909090e6
    Reac282 = smodel.Reac('Reac282', vsys, lhs = [CaM3Ca_PDE1_CaMKII], rhs = [CaM3Ca_PDE1])
    Reac282.kcst = 8
    Reac283 = smodel.Reac('Reac283', vsys, lhs = [CaM3Ca_PDE1_CaMKII], rhs = [CaM3Ca_pPDE1])
    Reac283.kcst = 2

    #CaM3Ca_pPDE1 + CaN <-> CaM3Ca_pPDE1_CaN -> CaM3Ca_PDE1 + CaN
    Reac284 = smodel.Reac('Reac284', vsys, lhs = [CaM3Ca_pPDE1, CaM3CaCaN], rhs = [CaM3Ca_pPDE1_CaN])
    Reac284.kcst = 1.25e6
    Reac285 = smodel.Reac('Reac285', vsys, lhs = [CaM3Ca_pPDE1_CaN], rhs = [CaM3Ca_pPDE1, CaM3CaCaN])
    Reac285.kcst = 2 
    Reac286 = smodel.Reac('Reac286', vsys, lhs = [CaM3Ca_pPDE1_CaN], rhs = [CaM3Ca_PDE1, CaM3CaCaN])
    Reac286.kcst = 0.5


    #PDE1 + CaM3Ca <-> CaM3Ca_PDE1 
    Reac287 = smodel.Reac('Reac287', vsys, lhs = [PDE1,CaM3Ca], rhs = [CaM3Ca_PDE1])
    Reac287.kcst = 600e6
    Reac323 = smodel.Reac('Reac323', vsys, lhs = [CaM3Ca_PDE1], rhs = [PDE1,CaM3Ca])
    Reac323.kcst = 0.06 

    #pPDE1 + CaM3Ca <-> CaM3Ca_pPDE1 
    Reac288 = smodel.Reac('Reac288', vsys, lhs = [pPDE1,CaM3Ca], rhs = [CaM3Ca_pPDE1])
    Reac288.kcst = 600e6
    Reac324 = smodel.Reac('Reac324', vsys, lhs = [CaM3Ca_pPDE1], rhs = [pPDE1,CaM3Ca])
    Reac324.kcst = 0.36 

    #PP2A + pG <-> PP2A_pGsub
    Reac289 = smodel.Reac('Reac289', vsys, lhs = [PP2A,pG], rhs = [PP2A_pGsub])
    Reac289.kcst = 10e6
    Reac325 = smodel.Reac('Reac325', vsys, lhs = [PP2A_pGsub], rhs = [PP2A,pG])
    Reac325.kcst = 0.06

    #pG -> G_sub 
    Reac290 = smodel.Reac('Reac290', vsys, lhs = [pG], rhs = [G_sub])
    Reac290.kcst = 0.2

    #pG + PP2A <-> pG_PP2A -> G_sub + PP2A
    Reac291 = smodel.Reac('Reac291', vsys, lhs = [pG,PP2A], rhs = [pG_PP2A])
    Reac291.kcst = 2e6
    Reac292 = smodel.Reac('Reac292', vsys, lhs = [pG_PP2A], rhs = [pG,PP2A])
    Reac292.kcst = 8
    Reac293 = smodel.Reac('Reac293', vsys, lhs = [pG_PP2A], rhs = [G_sub, PP2A]) 
    Reac293.kcst = 2

    #pG + CaM3CaCaN <-> pG_CaM3CaCaN -> G_sub + CaM3CaCaN
    Reac294 = smodel.Reac('Reac294', vsys, lhs = [pG,CaM3CaCaN], rhs = [pG_CaM3CaCaN])
    Reac294.kcst = 1.5625e6
    Reac295 = smodel.Reac('Reac295', vsys, lhs = [pG_CaM3CaCaN], rhs = [pG,CaM3CaCaN])
    Reac295.kcst = 2
    Reac296 = smodel.Reac('Reac296', vsys, lhs = [pG_CaM3CaCaN], rhs = [G_sub, CaM3CaCaN]) 
    Reac296.kcst = 0.5 

    #G_sub + PKG_cGMP <-> G_sub_PKG -> pG + PKG
    Reac297 = smodel.Reac('Reac297', vsys, lhs = [G_sub,PKG_cGMP], rhs = [G_sub_PKG])
    Reac297.kcst = 50e6
    Reac298 = smodel.Reac('Reac298', vsys, lhs = [G_sub_PKG], rhs = [G_sub, PKG_cGMP])
    Reac298.kcst = 8
    Reac299 = smodel.Reac('Reac299', vsys, lhs = [G_sub_PKG], rhs = [pG, PKG_cGMP])
    Reac299.kcst = 2
    
    
    
    #PDE5 + cGMP + cGMP <-> act_PDE5
    Reac300 = smodel.Reac('Reac300', vsys, lhs= [PDE5,cGMP,cGMP], rhs = [act_PDE5])
    Reac300.kcst = 1e12
    Reac301 = smodel.Reac('Reac301', vsys, lhs = [act_PDE5], rhs = [PDE5, cGMP, cGMP])
    Reac301.kcst = 0.25 

    #PKG + cGMP + cGMP <-> PKG_cGMP
    Reac302 = smodel.Reac('Reac302', vsys, lhs= [PKG,cGMP,cGMP], rhs = [PKG_cGMP])
    Reac302.kcst = 2e12
    Reac303 = smodel.Reac('Reac303', vsys, lhs = [PKG_cGMP], rhs = [PKG, cGMP, cGMP])
    Reac303.kcst = 0.1

    #PP1_DARPP32 + C_actPKA <-> PP1_DARPP32_C_actPKA -> PP1_pDARPP32 + C_actPKA 
    Reac326 = smodel.Reac('Reac326', vsys, lhs = [PP1_DARPP32,C_actPKA], rhs = [PP1_DARPP32_C_actPKA])
    Reac326.kcst = 5.625e6
    Reac327 = smodel.Reac('Reac327', vsys, lhs = [PP1_DARPP32_C_actPKA], rhs = [PP1_DARPP32, C_actPKA])
    Reac327.kcst = 10.8
    Reac328 = smodel.Reac('Reac328', vsys, lhs = [PP1_DARPP32_C_actPKA], rhs = [PP1_pDARPP32,C_actPKA])
    Reac328.kcst = 2.7

    #PP1_pDARPP32 + CaM3CaCaN <-> PP1_pDARPP32_CaN -> PP1_DARPP32 + CaM3CaCaN 
    Reac329 = smodel.Reac('Reac329', vsys, lhs = [PP1_pDARPP32,CaM3CaCaN], rhs = [PP1_pDARPP32_CaN])
    Reac329.kcst = 1.5625e6
    Reac330 = smodel.Reac('Reac330', vsys, lhs = [PP1_pDARPP32_CaN], rhs = [PP1_pDARPP32, CaM3CaCaN])
    Reac330.kcst = 2.0
    Reac331 = smodel.Reac('Reac331', vsys, lhs = [PP1_pDARPP32_CaN], rhs = [PP1_DARPP32,CaM3CaCaN])
    Reac331.kcst = 0.5

    #PP1_pDARPP32 + PP2A <-> PP1_pDARPP32_PP2A -> PP1_DARPP32 + PP2A 
    Reac332 = smodel.Reac('Reac332', vsys, lhs = [PP1_pDARPP32,PP2A], rhs = [PP1_pDARPP32_PP2A])
    Reac332.kcst = 2e6
    Reac333 = smodel.Reac('Reac333', vsys, lhs = [PP1_pDARPP32_PP2A], rhs = [PP1_pDARPP32, PP2A])
    Reac333.kcst = 8.0
    Reac334 = smodel.Reac('Reac334', vsys, lhs = [PP1_pDARPP32_PP2A], rhs = [PP1_DARPP32,PP2A])
    Reac334.kcst = 2.0
    
    #DARPP32 + C_actPKA <-> DARPP32_C_actPKA -> pDARPP32 + C_actPKA 
    Reac335 = smodel.Reac('Reac335', vsys, lhs = [DARPP32,C_actPKA], rhs = [DARPP32_C_actPKA])
    Reac335.kcst = 5.625e6
    Reac336 = smodel.Reac('Reac336', vsys, lhs = [DARPP32_C_actPKA], rhs = [DARPP32, C_actPKA])
    Reac336.kcst = 10.8
    Reac337 = smodel.Reac('Reac337', vsys, lhs = [DARPP32_C_actPKA], rhs = [pDARPP32,C_actPKA])
    Reac337.kcst = 2.7

    #pDARPP32 + CaM3CaCaN <-> pDARPP32_CaN -> DARPP32 + CaM3CaCaN 
    Reac338 = smodel.Reac('Reac338', vsys, lhs = [pDARPP32,CaM3CaCaN], rhs = [pDARPP32_CaN])
    Reac338.kcst = 1.5625e6
    Reac339 = smodel.Reac('Reac339', vsys, lhs = [pDARPP32_CaN], rhs = [pDARPP32, CaM3CaCaN])
    Reac339.kcst = 2.0
    Reac340 = smodel.Reac('Reac340', vsys, lhs = [pDARPP32_CaN], rhs = [DARPP32,CaM3CaCaN])
    Reac340.kcst = 0.5

    #pDARPP32 + PP2A <-> pDARPP32_PP2A -> DARPP32 + PP2A 
    Reac341 = smodel.Reac('Reac341', vsys, lhs = [pDARPP32,PP2A], rhs = [pDARPP32_PP2A])
    Reac341.kcst = 2.0e6
    Reac342 = smodel.Reac('Reac342', vsys, lhs = [pDARPP32_PP2A], rhs = [pDARPP32,PP2A])
    Reac342.kcst = 8.0
    Reac343 = smodel.Reac('Reac343', vsys, lhs = [pDARPP32_PP2A], rhs = [DARPP32,PP2A])
    Reac343.kcst = 2.0
    
    #PP1 + DARPP32 <-> PP1_DARPP32 
    Reac344 = smodel.Reac('Reac344', vsys, lhs = [PP1, DARPP32], rhs = [ PP1_DARPP32])
    Reac344.kcst = 0.5e6
    Reac345 = smodel.Reac('Reac345', vsys, lhs = [PP1_DARPP32], rhs = [PP1, DARPP32])
    Reac345.kcst = 0.5

    #PP1 + pDARPP32 <-> PP1_pDARPP32 
    Reac346 = smodel.Reac('Reac346', vsys, lhs = [PP1, pDARPP32], rhs = [ PP1_pDARPP32])
    Reac346.kcst = 500e6
    Reac347 = smodel.Reac('Reac347', vsys, lhs = [PP1_pDARPP32], rhs = [PP1, pDARPP32])
    Reac347.kcst = 0.5   

    #R2C2_PKA + cAMP <-> cAMP_R2C2 
    Reac348 = smodel.Reac('Reac348', vsys, lhs = [R2C2_PKA,cAMP], rhs = [cAMP_R2C2])
    Reac348.kcst = 2e6
    Reac349 = smodel.Reac('Reac349', vsys, lhs = [cAMP_R2C2], rhs = [R2C2_PKA,cAMP])
    Reac349.kcst = 0.75

    #cAMP_R2C2 + cAMP <-> cAMP2_bb_R2C2 
    Reac350 = smodel.Reac('Reac350', vsys, lhs = [cAMP_R2C2,cAMP], rhs = [cAMP2_bb_R2C2])
    Reac350.kcst = 1e6
    Reac351 = smodel.Reac('Reac351', vsys, lhs = [cAMP2_bb_R2C2], rhs = [cAMP_R2C2,cAMP])
    Reac351.kcst = 1.5
    
    #cAMP_R2C2 + cAMP <-> cAMP2_ab_R2C2 
    Reac352 = smodel.Reac('Reac352', vsys, lhs = [cAMP_R2C2,cAMP], rhs = [cAMP2_ab_R2C2])
    Reac352.kcst = 10e6
    Reac353 = smodel.Reac('Reac353', vsys, lhs = [cAMP2_ab_R2C2], rhs = [cAMP_R2C2,cAMP])
    Reac353.kcst = 7.5
    
    #cAMP2_bb_R2C2 + cAMP <-> cAMP3_R2C2 
    Reac354 = smodel.Reac('Reac354', vsys, lhs = [cAMP2_bb_R2C2, cAMP], rhs = [cAMP3_R2C2])
    Reac354.kcst = 20e6
    Reac355 = smodel.Reac('Reac355', vsys, lhs = [cAMP3_R2C2], rhs = [cAMP2_bb_R2C2, cAMP])
    Reac355.kcst = 7.5 
    
    
    #cAMP2_ab_R2C2 + cAMP <-> cAMP3_R2C2 
    Reac356 = smodel.Reac('Reac356', vsys, lhs = [cAMP2_ab_R2C2, cAMP], rhs = [cAMP3_R2C2])
    Reac356.kcst = 1.0e6
    Reac357 = smodel.Reac('Reac357', vsys, lhs = [cAMP3_R2C2], rhs = [cAMP2_ab_R2C2, cAMP])
    Reac357.kcst = 0.75  

    #cAMP3_R2C2 + cAMP <-> cAMP4_R2C2 
    Reac358 = smodel.Reac('Reac358', vsys, lhs = [cAMP3_R2C2, cAMP], rhs = [cAMP4_R2C2])
    Reac358.kcst = 10e6
    Reac359 = smodel.Reac('Reac359', vsys, lhs = [cAMP4_R2C2], rhs = [cAMP3_R2C2,cAMP])
    Reac359.kcst = 15

    #cAMP2_ab_R2C2  <-> cAMP2_ab_R2C + C_actPKA
    Reac360 = smodel.Reac('Reac360', vsys, lhs = [cAMP2_ab_R2C2], rhs = [cAMP2_ab_R2C, C_actPKA])
    Reac360.kcst = 0.005
    Reac361 = smodel.Reac('Reac361', vsys, lhs = [cAMP2_ab_R2C, C_actPKA], rhs = [cAMP2_ab_R2C2])
    Reac361.kcst = 5e6

    #cAMP3_R2C2  <-> cAMP3_R2C + C_actPKA
    Reac362 = smodel.Reac('Reac362', vsys, lhs = [cAMP3_R2C2], rhs = [cAMP3_R2C, C_actPKA])
    Reac362.kcst = 0.005
    Reac363 = smodel.Reac('Reac363', vsys, lhs = [cAMP3_R2C, C_actPKA], rhs = [cAMP3_R2C2])
    Reac363.kcst = 5e6
    
    #cAMP4_R2C2  <-> cAMP4_R2C + C_actPKA
    Reac364 = smodel.Reac('Reac364', vsys, lhs = [cAMP4_R2C2], rhs = [cAMP4_R2C, C_actPKA])
    Reac364.kcst = 6
    Reac365 = smodel.Reac('Reac365', vsys, lhs = [cAMP4_R2C, C_actPKA], rhs = [cAMP4_R2C2])
    Reac365.kcst = 5e6
    
    #cAMP4_R2C  <-> cAMP4_R2 + C_actPKA
    Reac366 = smodel.Reac('Reac366', vsys, lhs = [cAMP4_R2C], rhs = [cAMP4_R2, C_actPKA])
    Reac366.kcst = 3
    Reac367 = smodel.Reac('Reac367', vsys, lhs = [cAMP4_R2, C_actPKA], rhs = [cAMP4_R2C])
    Reac367.kcst = 10e6

    #cAMP2_ab_R2C + cAMP <-> cAMP3_R2C  
    Reac368 = smodel.Reac('Reac368', vsys, lhs = [cAMP2_ab_R2C, cAMP], rhs = [cAMP3_R2C])
    Reac368.kcst = 1.0e6
    Reac369 = smodel.Reac('Reac369', vsys, lhs = [cAMP3_R2C], rhs = [cAMP2_ab_R2C, cAMP])
    Reac369.kcst =  0.75

    #cAMP3_R2C + cAMP <-> cAMP4_R2C 
    Reac370 = smodel.Reac('Reac370', vsys, lhs = [cAMP3_R2C, cAMP], rhs = [cAMP4_R2C])
    Reac370.kcst = 10e6
    Reac371 = smodel.Reac('Reac371', vsys, lhs = [cAMP4_R2C], rhs = [cAMP3_R2C,cAMP])
    Reac371.kcst = 7.5

    #cAMP + PDE4 <-> cAMP_PDE4 <-> AMP + PDE4
    Reac372 = smodel.Reac('Reac372',vsys, lhs = [cAMP,PDE4], rhs = [cAMP_PDE4])
    Reac372.kcst = 0.125e6
    Reac373 = smodel.Reac('Reac373',vsys, lhs = [cAMP_PDE4], rhs = [cAMP,PDE4])
    Reac373.kcst = 0.2
    Reac374 = smodel.Reac('Reac374',vsys, lhs = [cAMP_PDE4], rhs = [AMP,PDE4])
    Reac374.kcst = 0.05

    #cAMP + CaM3Ca_pPDE1 <-> cAMP_CaM3Ca_pPDE1 <-> AMP + CaM3Ca_pPDE1
    Reac375 = smodel.Reac('Reac375',vsys, lhs = [cAMP,CaM3Ca_pPDE1], rhs = [cAMP_CaM3Ca_pPDE1])
    Reac375.kcst = 2.0833e6
    Reac376 = smodel.Reac('Reac376',vsys, lhs = [cAMP_CaM3Ca_pPDE1], rhs = [cAMP,CaM3Ca_pPDE1])
    Reac376.kcst = 20
    Reac377 = smodel.Reac('Reac377',vsys, lhs = [cAMP_CaM3Ca_pPDE1], rhs = [AMP,CaM3Ca_pPDE1])
    Reac377.kcst = 5

    #cAMP + CaM3Ca_PDE1 <-> cAMP_CaM3Ca_PDE1 <-> AMP + CaM3Ca_PDE1
    Reac378 = smodel.Reac('Reac378',vsys, lhs = [cAMP,CaM3Ca_PDE1], rhs = [cAMP_CaM3Ca_PDE1])
    Reac378.kcst = 2.0833e6
    Reac379 = smodel.Reac('Reac379',vsys, lhs = [cAMP_CaM3Ca_PDE1], rhs = [cAMP,CaM3Ca_PDE1])
    Reac379.kcst = 20
    Reac380 = smodel.Reac('Reac380',vsys, lhs = [cAMP_CaM3Ca_PDE1], rhs = [AMP,CaM3Ca_PDE1])
    Reac380.kcst = 5

    #cAMP + pPDE1 <-> cAMP_pPDE1 <-> AMP + pPDE1
    Reac381 = smodel.Reac('Reac381',vsys, lhs = [cAMP,pPDE1], rhs = [cAMP_pPDE1])
    Reac381.kcst = 0.0416e6
    Reac382 = smodel.Reac('Reac382',vsys, lhs = [cAMP_pPDE1], rhs = [cAMP,pPDE1])
    Reac382.kcst = 0.4
    Reac383 = smodel.Reac('Reac383',vsys, lhs = [cAMP_pPDE1], rhs = [AMP,pPDE1])
    Reac383.kcst = 0.1

    #cAMP + PDE1 <-> cAMP_PDE1 <-> AMP + PDE1
    Reac384 = smodel.Reac('Reac384',vsys, lhs = [cAMP,PDE1], rhs = [cAMP_PDE1])
    Reac384.kcst = 0.0416e6
    Reac385 = smodel.Reac('Reac385',vsys, lhs = [cAMP_PDE1], rhs = [cAMP,PDE1])
    Reac385.kcst = 0.4
    Reac386 = smodel.Reac('Reac386',vsys, lhs = [cAMP_PDE1], rhs = [AMP,PDE1])
    Reac386.kcst = 0.1

    # APC + PLA2_PIP2 <-> APC_PLA2_PIP2 -> AA + PLA2_PIP2 
    Reac400 = smodel.Reac('Reac400',vsys, lhs = [APC, PLA2_PIP2], rhs = [APC_PLA2_PIP2])
    Reac400.kcst = 2.76e6
    Reac401 = smodel.Reac('Reac401',vsys, lhs = [APC_PLA2_PIP2], rhs = [APC, PLA2_PIP2])
    Reac401.kcst = 44.16
    Reac402 = smodel.Reac('Reac402',vsys, lhs = [APC_PLA2_PIP2], rhs = [AA, PLA2_PIP2])
    Reac402.kcst = 11.04
    
    # APC + pPLA2_Ca <-> APC_pPLA2_Ca -> AA + pPLA2_Ca 
    Reac403 = smodel.Reac('Reac403',vsys, lhs = [APC, pPLA2_Ca], rhs = [APC_pPLA2_Ca])
    Reac403.kcst = 30e6
    Reac404 = smodel.Reac('Reac404',vsys, lhs = [APC_pPLA2_Ca], rhs = [APC, pPLA2_Ca])
    Reac404.kcst = 480
    Reac405 = smodel.Reac('Reac405',vsys, lhs = [APC_pPLA2_Ca], rhs = [AA, pPLA2_Ca])
    Reac405.kcst = 120

    # APC + PLA2_Ca <-> APC_PLA2_Ca -> AA + PLA2_Ca 
    Reac406 = smodel.Reac('Reac406',vsys, lhs = [APC, PLA2_Ca], rhs = [APC_PLA2_Ca])
    Reac406.kcst = 13.5e6
    Reac407 = smodel.Reac('Reac407',vsys, lhs = [APC_PLA2_Ca], rhs = [APC, PLA2_Ca])
    Reac407.kcst = 216.0
    Reac408 = smodel.Reac('Reac408',vsys, lhs = [APC_PLA2_Ca], rhs = [AA, PLA2_Ca])
    Reac408.kcst = 54

    # APC + pPLA2 <-> APC_pPLA2 -> AA + pPLA2 
    Reac410 = smodel.Reac('Reac410',vsys, lhs = [APC, pPLA2], rhs = [APC_pPLA2])
    Reac410.kcst = 30e6
    Reac411 = smodel.Reac('Reac411',vsys, lhs = [APC_pPLA2], rhs = [APC, pPLA2])
    Reac411.kcst = 480
    Reac412 = smodel.Reac('Reac412',vsys, lhs = [APC_pPLA2], rhs = [AA, pPLA2])
    Reac412.kcst = 120

    # APC + PLA2_PIP2_Ca <-> APC_PLA2_PIP2_Ca -> AA + PLA2_PIP2_Ca 
    Reac413 = smodel.Reac('Reac413',vsys, lhs = [APC, PLA2_PIP2_Ca], rhs = [APC_PLA2_PIP2_Ca])
    Reac413.kcst = 9e6
    Reac414 = smodel.Reac('Reac414',vsys, lhs = [APC_PLA2_PIP2_Ca], rhs = [APC, PLA2_PIP2_Ca])
    Reac414.kcst = 144
    Reac415 = smodel.Reac('Reac415',vsys, lhs = [APC_PLA2_PIP2_Ca], rhs = [AA, PLA2_PIP2_Ca])
    Reac415.kcst = 36

    # APC + DAG_PLA2_Ca <-> APC_DAG_PLA2_Ca -> AA + DAG_PLA2_Ca 
    Reac416 = smodel.Reac('Reac416',vsys, lhs = [APC, DAG_PLA2_Ca], rhs = [APC_DAG_PLA2_Ca])
    Reac416.kcst = 15e6
    Reac417 = smodel.Reac('Reac417',vsys, lhs = [APC_DAG_PLA2_Ca], rhs = [APC, DAG_PLA2_Ca])
    Reac417.kcst = 240
    Reac418 = smodel.Reac('Reac418',vsys, lhs = [APC_DAG_PLA2_Ca], rhs = [AA, DAG_PLA2_Ca])
    Reac418.kcst = 60

    # AA -> AA_deg 
    Reac419 = smodel.Reac('Reac419',vsys, lhs = [AA], rhs = [AA_deg])
    Reac419.kcst = 0.5

    # PLA2 + MAPK <-> PLA2_MAPK -> pPLA2 
    Reac420 = smodel.Reac('Reac420',vsys, lhs = [act_MAPK, PLA2], rhs = [PLA2_MAPK])
    Reac420.kcst = 3.91e6
    Reac421 = smodel.Reac('Reac421',vsys, lhs = [PLA2_MAPK], rhs = [act_MAPK, PLA2])
    Reac421.kcst = 80
    Reac422 = smodel.Reac('Reac422',vsys, lhs = [PLA2_MAPK], rhs = [act_MAPK, pPLA2])
    Reac422.kcst = 20

    # PLA2 + PIP2 <-> PLA2_PIP2 
    Reac423 = smodel.Reac('Reac423', vsys, lhs = [PLA2,PIP2], rhs = [PLA2_PIP2])
    Reac423.kcst = 0.0012e6
    Reac424 = smodel.Reac('Reac424', vsys, lhs = [PLA2_PIP2], rhs = [PLA2,PIP2])
    Reac424.kcst = 0.48

    # PLA2 + Ca <-> PLA2_Ca 
    Reac425 = smodel.Reac('Reac425', vsys, lhs = [PLA2,Ca], rhs = [PLA2_Ca])
    Reac425.kcst = 0.1e6
    Reac426 = smodel.Reac('Reac426', vsys, lhs = [PLA2_Ca], rhs = [PLA2,Ca])
    Reac426.kcst = 0.1
    
    # PLA2_PIP2 + Ca <-> PLA2_PIP2_Ca
    Reac427 = smodel.Reac('Reac427', vsys, lhs = [PLA2_PIP2,Ca], rhs = [PLA2_PIP2_Ca])
    Reac427.kcst = 0.1e6
    Reac428 = smodel.Reac('Reac428', vsys, lhs = [PLA2_PIP2_Ca], rhs = [PLA2_PIP2,Ca])
    Reac428.kcst = 0.1
    
    # PLA2_Ca + DAG <-> DAG_PLA2_Ca 
    Reac429 = smodel.Reac('Reac429', vsys, lhs = [PLA2_Ca,DAG], rhs = [DAG_PLA2_Ca])
    Reac429.kcst = 0.05e6
    Reac430 = smodel.Reac('Reac430', vsys, lhs = [DAG_PLA2_Ca], rhs = [PLA2_Ca,DAG])
    Reac430.kcst = 0.1
    
    # pPLA2 -> PLA2 
    Reac431 = smodel.Reac('Reac431', vsys, lhs = [pPLA2], rhs = [PLA2])
    Reac431.kcst = 0.17

    # pPLA2 + Ca <-> pPLA2_Ca 
    Reac432 = smodel.Reac('Reac432', vsys, lhs = [pPLA2,Ca], rhs = [pPLA2_Ca])
    Reac432.kcst = 6e6
    Reac433 = smodel.Reac('Reac433', vsys, lhs = [pPLA2_Ca], rhs = [pPLA2,Ca])
    Reac433.kcst = 0.1

    # PLA2_Ca + PIP2 <-> PLA2_PIP2_Ca
    Reac434 = smodel.Reac('Reac434', vsys, lhs = [PLA2_Ca,PIP2], rhs = [PLA2_PIP2_Ca])
    Reac434.kcst = 0.0012e6 
    Reac435 = smodel.Reac('Reac435', vsys, lhs = [PLA2_PIP2_Ca], rhs = [PLA2_Ca,PIP2])
    Reac435.kcst = 0.48

    # Raf <-> Raf_PKC -> act_Raf 
    Reac436 = smodel.Reac('Reac436',vsys, lhs = [Raf,totPKC], rhs = [Raf_PKC])
    Reac436.kcst = 0.0146e6
    Reac437 = smodel.Reac('Reac437',vsys, lhs = [Raf_PKC], rhs = [Raf])
    Reac437.kcst = 0.134
    Reac438 = smodel.Reac('Reac438',vsys, lhs = [Raf_PKC], rhs = [act_Raf])
    Reac438.kcst = 0.0335

    # act_Raf + PP2A <-> act_Raf_PP2A -> Raf + PP2A
    Reac445 = smodel.Reac('Reac445', vsys, lhs = [act_Raf, PP2A], rhs = [act_Raf_PP2A])
    Reac445.kcst = 2e6
    Reac446 = smodel.Reac('Reac446', vsys, lhs = [act_Raf_PP2A], rhs = [act_Raf, PP2A])
    Reac446.kcst = 8
    Reac447 = smodel.Reac('Reac447', vsys, lhs = [act_Raf_PP2A], rhs = [Raf, PP2A])
    Reac447.kcst = 2

    #MAPKK + act_Raf <-> MAPKK_Raf -> MAPKK_ser + act_Raf
    Reac439 = smodel.Reac('Reac439',vsys, lhs = [MAPKK, act_Raf], rhs = [MAPKK_Raf])
    Reac439.kcst = 1.32e6
    Reac440 = smodel.Reac('Reac440',vsys, lhs = [MAPKK_Raf], rhs = [MAPKK, act_Raf])
    Reac440.kcst = 0.42
    Reac441 = smodel.Reac('Reac441',vsys, lhs = [MAPKK_Raf], rhs = [act_MAPKK,act_Raf])
    Reac441.kcst = 0.105

    #MAPKK_ser + Raf <-> MAPKK_ser_Raf -> act_MAPKK + Raf
    Reac442 = smodel.Reac('Reac442',vsys, lhs = [MAPKK_ser, act_Raf], rhs = [MAPKK_ser_Raf])
    Reac442.kcst = 1.32e6 
    Reac443 = smodel.Reac('Reac443',vsys, lhs = [MAPKK_ser_Raf], rhs = [MAPKK_ser, act_Raf])
    Reac443.kcst = 0.42
    Reac444 = smodel.Reac('Reac444',vsys, lhs = [MAPKK_ser_Raf], rhs = [MAPKK_ser,act_Raf])
    Reac444.kcst = 0.105

    
    # act_MAPKK + PP2A <-> act_MAPKK_PP2A -> MAPKK_ser + PP2A
    Reac448 = smodel.Reac('Reac448', vsys, lhs = [act_MAPKK, PP2A], rhs = [act_MAPKK_PP2A])
    Reac448.kcst = 2e6
    Reac449 = smodel.Reac('Reac449', vsys, lhs = [act_MAPKK_PP2A], rhs = [act_MAPKK, PP2A])
    Reac449.kcst = 8
    Reac450 = smodel.Reac('Reac450', vsys, lhs = [act_MAPKK_PP2A], rhs = [MAPKK_ser, PP2A])
    Reac450.kcst = 2

    # MAPKK_ser + PP2A <-> MAPKK_ser_PP2A -> MAPKK + PP2A
    Reac451 = smodel.Reac('Reac451', vsys, lhs = [MAPKK_ser, PP2A], rhs = [MAPKK_ser_PP2A])
    Reac451.kcst = 2e6
    Reac452 = smodel.Reac('Reac452', vsys, lhs = [MAPKK_ser_PP2A], rhs = [MAPKK_ser, PP2A])
    Reac452.kcst = 8
    Reac453 = smodel.Reac('Reac453', vsys, lhs = [MAPKK_ser_PP2A], rhs = [MAPKK, PP2A])
    Reac453.kcst = 2

    # act_MAPK + MKP_1 <-> act_MAPK_MKP_1 -> MAPK_tyr + MKP_1
    Reac454 = smodel.Reac('Reac454', vsys, lhs = [act_MAPK, MKP_1], rhs = [act_MAPK_MKP_1])
    Reac454.kcst = 30e6
    Reac455 = smodel.Reac('Reac455', vsys, lhs = [act_MAPK_MKP_1], rhs = [act_MAPK, MKP_1])
    Reac455.kcst = 4
    Reac456 = smodel.Reac('Reac456', vsys, lhs = [act_MAPK_MKP_1], rhs = [MAPK_tyr, MKP_1])
    Reac456.kcst = 1

    # MAPK_tyr + MKP_1 <-> MAPK_tyr_MKP_1 -> MAPK + MKP_1
    Reac457 = smodel.Reac('Reac457', vsys, lhs = [MAPK_tyr, MKP_1], rhs = [MAPK_tyr_MKP_1])
    Reac457.kcst = 30e6
    Reac458 = smodel.Reac('Reac458', vsys, lhs = [MAPK_tyr_MKP_1], rhs = [MAPK_tyr, MKP_1])
    Reac458.kcst = 4
    Reac459 = smodel.Reac('Reac459', vsys, lhs = [MAPK_tyr_MKP_1], rhs = [MAPK, MKP_1])
    Reac459.kcst = 1

    # MAPK + MAPKK <-> MAPK_MAPKK -> MAPK_tyr + MAPKK
    Reac460 = smodel.Reac('Reac460', vsys, lhs = [MAPK, act_MAPKK], rhs = [MAPK_MAPKK])
    Reac460.kcst = 16.2e6
    Reac461 = smodel.Reac('Reac461', vsys, lhs = [MAPK_MAPKK], rhs = [MAPK, act_MAPKK])
    Reac461.kcst = 0.6
    Reac462 = smodel.Reac('Reac462', vsys, lhs = [MAPK_MAPKK], rhs = [MAPK_tyr, act_MAPKK])
    Reac462.kcst = 0.15 

    # MAPK_tyr + MAPKK <-> MAPK_tyr_MAPKK -> act_MAPK + MAPKK
    Reac463 = smodel.Reac('Reac463', vsys, lhs = [MAPK_tyr, act_MAPKK], rhs = [MAPK_tyr_MAPKK])
    Reac463.kcst = 16.2e6
    Reac464 = smodel.Reac('Reac464', vsys, lhs = [MAPK_tyr_MAPKK], rhs = [MAPK_tyr, act_MAPKK])
    Reac464.kcst = 0.6
    Reac465 = smodel.Reac('Reac465', vsys, lhs = [MAPK_tyr_MAPKK], rhs = [act_MAPK, act_MAPKK])
    Reac465.kcst = 0.15 

    # PKC + AA <-> PKC_AA
    Reac466 = smodel.Reac('Reac466', vsys, lhs = [PKC,AA] , rhs = [PKC_AA])
    Reac466.kcst = 0.2e6 
    Reac467 = smodel.Reac('Reac467', vsys, lhs = [PKC_AA] , rhs = [PKC,AA])
    Reac467.kcst = 10

    # PKC_AA + Ca + Ca <-> PKC_Ca_AA
    Reac468 = smodel.Reac('Reac468', vsys, lhs = [PKC_AA,Ca,Ca] , rhs = [PKC_Ca_AA])
    Reac468.kcst = 1e12
    Reac469 = smodel.Reac('Reac469', vsys, lhs = [PKC_Ca_AA] , rhs = [PKC_AA,Ca,Ca])
    Reac469.kcst = 10

    # PKC_AA + DAG <-> PKC_DAG_AA
    Reac470 = smodel.Reac('Reac470', vsys, lhs = [PKC_AA,DAG] , rhs = [PKC_DAG_AA])
    Reac470.kcst = 4e6
    Reac471 = smodel.Reac('Reac471', vsys, lhs = [PKC_DAG_AA] , rhs = [PKC_AA,DAG])
    Reac471.kcst = 0.02

    # PKC_DAG_AA + Ca + Ca <-> PKC_Ca_DAG_AA
    Reac472 = smodel.Reac('Reac472', vsys, lhs = [PKC_DAG_AA,Ca,Ca] , rhs = [PKC_Ca_DAG_AA])
    Reac472.kcst = 1e12
    Reac473 = smodel.Reac('Reac473', vsys, lhs = [PKC_Ca_DAG_AA] , rhs = [PKC_DAG_AA,Ca,Ca])
    Reac473.kcst = 10

    # PKC_Ca_DAG + AA  <-> PKC_Ca_DAG_AA
    Reac474 = smodel.Reac('Reac474', vsys, lhs = [PKC_Ca_DAG,AA] , rhs = [PKC_Ca_DAG_AA])
    Reac474.kcst = 0.2e6
    Reac475 = smodel.Reac('Reac475', vsys, lhs = [PKC_Ca_DAG_AA] , rhs = [PKC_Ca_DAG,AA])
    Reac475.kcst = 10

    # PKCCamemb + DAG <-> PKC_Ca_DAG
    Reac476 = smodel.Reac('Reac476', vsys, lhs = [PKCCamemb,DAG] , rhs = [PKC_Ca_DAG])
    Reac476.kcst = 2e6
    Reac477 = smodel.Reac('Reac477', vsys, lhs = [PKC_Ca_DAG] , rhs = [PKCCamemb,DAG])
    Reac477.kcst = 0.02

    # PKCCamemb + AA <-> PKC_Ca_AA
    Reac478 = smodel.Reac('Reac478', vsys, lhs = [PKCCamemb,AA] , rhs = [PKC_Ca_AA])
    Reac478.kcst = 0.2e6
    Reac479 = smodel.Reac('Reac479', vsys, lhs = [PKC_Ca_AA] , rhs = [PKCCamemb,AA])
    Reac479.kcst = 10

    # PKC + Ca + Ca <-> PKCCacyto
    Reac480 = smodel.Reac('Reac480', vsys, lhs = [PKC,Ca,Ca] , rhs = [PKCCacyto])
    Reac480.kcst = 1e12
    Reac481 = smodel.Reac('Reac481', vsys, lhs = [PKCCacyto] , rhs = [PKC,Ca,Ca])
    Reac481.kcst = 10

    # PKCCacyto <-> PKCCamemb
    Reac482 = smodel.Reac('Reac482', vsys, lhs = [PKCCacyto] , rhs = [PKCCamemb])
    Reac482.kcst = 1
    Reac483 = smodel.Reac('Reac483', vsys, lhs = [PKCCamemb] , rhs = [PKCCacyto])
    Reac483.kcst = 0.05

    # AMPAR  <-> totPKC_AMPAR -> pAMPAR  
    Reac484 = smodel.Reac('Reac484',vsys,  lhs = [AMPAR,totPKC], rhs = [totPKC_AMPAR])
    Reac484.kcst = 0.0714e6
    Reac485 = smodel.Reac('Reac485', vsys, lhs = [totPKC_AMPAR], rhs = [AMPAR])
    Reac485.kcst = 0.2 
    Reac486 = smodel.Reac('Reac486', vsys, lhs = [totPKC_AMPAR], rhs = [pAMPAR])
    Reac486.kcst = 0.05 

    # pAMPAR + PP2A <-> PP2A_pAMPAR -> AMPAR + PP2A 
    Reac487 = smodel.Reac('Reac487',vsys,  lhs = [pAMPAR,PP2A], rhs = [PP2A_pAMPAR])
    Reac487.kcst = 2e6
    Reac488 = smodel.Reac('Reac488', vsys, lhs = [PP2A_pAMPAR], rhs = [pAMPAR,PP2A])
    Reac488.kcst = 8
    Reac489 = smodel.Reac('Reac489', vsys, lhs = [PP2A_pAMPAR], rhs = [AMPAR,PP2A])
    Reac489.kcst = 2

    # GABAaR <-> GABAaR_CaMKII -> pGABAaR 
    Reac490 = smodel.Reac('Reac490',vsys,  lhs = [GABAaR,calc_3_1], rhs = [GABAaR_CaMKII])
    Reac490.kcst = 0.04545e6
    Reac491 = smodel.Reac('Reac491', vsys, lhs = [GABAaR_CaMKII], rhs = [GABAaR])
    Reac491.kcst = 4 
    Reac492 = smodel.Reac('Reac492', vsys, lhs = [GABAaR_CaMKII], rhs = [pGABAaR])
    Reac492.kcst = 1

    # pGABAaR + PP1 <-> pGABAaR_PP1 -> GABAaR + PP1 
    Reac493 = smodel.Reac('Reac493',vsys,  lhs = [pGABAaR,PP1], rhs = [pGABAaR_PP1])
    Reac493.kcst = 3.3333e6
    Reac494 = smodel.Reac('Reac494', vsys, lhs = [pGABAaR_PP1], rhs = [pGABAaR,PP1])
    Reac494.kcst = 8 
    Reac495 = smodel.Reac('Reac495', vsys, lhs = [pGABAaR_PP1], rhs = [GABAaR,PP1])
    Reac495.kcst = 2 

    #pGABAaR -> GABAaR 
    Reac496 = smodel.Reac('Reac496', vsys, lhs = [pGABAaR], rhs = [GABAaR])
    Reac496.kcst = 0.04 

    # DAG -> deg 
    Reac500 = smodel.Reac('Reac500', vsys, lhs = [DAG], rhs = [deg])
    Reac500.kcst = 10.0

    # IP3 -> deg 
    Reac501 = smodel.Reac('Reac501', vsys, lhs = [IP3], rhs = [deg])
    Reac501.kcst = 10.0

    # GTPaq + PLC -> PLC_Gq 
    Reac502 = smodel.Reac('Reac502', vsys, lhs = [GTPaq,PLC], rhs = [PLC_Gq])
    Reac502.kcst = 2.52e6
    Reac549 = smodel.Reac('Reac549', vsys, lhs = [PLC_Gq], rhs = [GTPaq,PLC])
    Reac549.kcst = 0.1
    
    # PLC_Gq -> PLC + GDPaq 
    Reac503 = smodel.Reac('Reac503', vsys, lhs = [PLC_Gq], rhs = [PLC,GDPaq])
    Reac503.kcst = 0.0666

    # GTPaq -> GDPaq 
    Reac504 = smodel.Reac('Reac504', vsys, lhs = [GTPaq], rhs = [GDPaq])
    Reac504.kcst = 0.0666

    # GTPas -> GDPas 
    Reac505 = smodel.Reac('Reac505', vsys, lhs = [GTPas], rhs = [GDPas])
    Reac505.kcst = 0.0666

    # GTPaq + bg -> GTPaqbg  
    Reac506 = smodel.Reac('Reac506', vsys, lhs = [GTPaq,bg], rhs = [GTPaqbg])
    Reac506.kcst = 0.01e6
    Reac600 = smodel.Reac('Reac600',vsys, lhs = [GTPasbg], rhs = [GTPas,bg])
    Reac600.kcst = 1.0

    # GTPas + bg -> GTPasbg
    Reac507 = smodel.Reac('Reac507', vsys, lhs = [GTPas,bg], rhs = [GTPasbg])
    Reac507.kcst = 0.01e6
    Reac601 = smodel.Reac('Reac601',vsys, lhs = [GTPasbg], rhs = [GTPas,bg])
    Reac601.kcst = 1.0

    # GDPaq + bg -> GDPaqbg 
    Reac508 = smodel.Reac('Reac508', vsys, lhs = [GDPaq,bg], rhs = [GDPaqbg])
    Reac508.kcst = 0.7e6
    Reac550 = smodel.Reac('Reac550',vsys, lhs = [GDPaqbg], rhs = [GDPaq,bg])
    Reac550.kcst = 0.0013

    # GDPas + bg -> GDPasbg 
    Reac509 = smodel.Reac('Reac509', vsys, lhs = [GDPas,bg], rhs = [GDPasbg])
    Reac509.kcst =0.7e6
    Reac551 = smodel.Reac('Reac551', vsys, lhs = [GDPasbg], rhs = [GDPas,bg])
    Reac551.kcst = 0.0013

    # GTPaqbg -> GDPaqbg 
    Reac510 = smodel.Reac('Reac510', vsys, lhs = [GTPaqbg],rhs = [GDPaqbg])
    Reac510.kcst = 0.0666 

    # GTPasbg -> GDPasbg 
    Reac511 = smodel.Reac('Reac511', vsys, lhs = [GTPasbg],rhs = [GDPasbg])
    Reac511.kcst = 0.0666

    # mGluR1 + GDPaqbg -> mGluR1_GDPaqbg 
    Reac512 = smodel.Reac('Reac512', vsys, lhs = [mGluR1,GDPaqbg], rhs = [mGluR1_GDPaqbg])
    Reac512.kcst = 0.2e6
    Reac552 = smodel.Reac('Reac552', vsys, lhs = [mGluR1_GDPaqbg], rhs = [mGluR1,GDPaqbg])
    Reac552.kcst = 0.1

    # mGluR1 + GDPasbg -> mGluR1_GDPasbg 
    Reac513 = smodel.Reac('Reac513', vsys, lhs = [mGluR1,GDPasbg], rhs = [mGluR1_GDPasbg])
    Reac513.kcst = 0.002e6
    Reac553 = smodel.Reac('Reac553', vsys, lhs = [mGluR1_GDPasbg], rhs = [mGluR1,GDPasbg])
    Reac553.kcst = 0.1

    # mGluR1_GDPaqbg + Glu <-> Glu_mGluR1_GDPaqbg 
    Reac514 = smodel.Reac('Reac514', vsys, lhs = [mGluR1_GDPaqbg,Glu], rhs = [Glu_mGluR1_GDPaqbg])
    Reac514.kcst = 1e6
    Reac515 = smodel.Reac('Reac515', vsys, lhs = [Glu_mGluR1_GDPaqbg], rhs = [mGluR1_GDPaqbg, Glu])
    Reac515.kcst = 10

    # mGluR1_GDPasbg + Glu <-> Glu_mGluR1_GDPasbg 
    Reac516 = smodel.Reac('Reac516', vsys, lhs = [mGluR1_GDPasbg,Glu], rhs = [Glu_mGluR1_GDPasbg])
    Reac516.kcst = 1e6
    Reac517 = smodel.Reac('Reac517', vsys, lhs = [Glu_mGluR1_GDPasbg], rhs = [mGluR1_GDPasbg, Glu])
    Reac517.kcst = 10
    
    # mGluR1 + Glu <-> Glu_mGluR1
    Reac518 = smodel.Reac('Reac518', vsys, lhs = [mGluR1,Glu], rhs = [Glu_mGluR1])
    Reac518.kcst = 1e6
    Reac519 = smodel.Reac('Reac519', vsys, lhs = [Glu_mGluR1], rhs = [mGluR1,Glu])
    Reac519.kcst = 10

    # GDPaqbg + Glu_mGLuR1 -> Glu_mGluR1_GDPaqbg 
    Reac520 = smodel.Reac('Reac520', vsys, lhs = [GDPaqbg, Glu_mGluR1], rhs = [Glu_mGluR1_GDPaqbg])
    Reac520.kcst = 10.0e6
    Reac554 = smodel.Reac('Reac554',vsys, lhs = [Glu_mGluR1_GDPaqbg], rhs = [GDPaqbg,Glu_mGluR1])
    Reac554.kcst = 0.1

    # GDPasbg + Glu_mGluR1 -> Glu_mGluR1_GDPasbg 
    Reac521 = smodel.Reac('Reac521', vsys, lhs = [GDPasbg, Glu_mGluR1], rhs = [Glu_mGluR1_GDPasbg])
    Reac521.kcst = 0.1e6
    Reac555 = smodel.Reac('Reac555', vsys, lhs = [Glu_mGluR1_GDPasbg], rhs = [GDPasbg,Glu_mGluR1]) 
    Reac555.kcst = 0.1

    # Glu_mGluR1_GDPaqbg -> Glu_mGluR1 + GTPaqbg
    Reac522 = smodel.Reac('Reac522', vsys, lhs = [Glu_mGluR1_GDPaqbg], rhs = [Glu_mGluR1,GTPaqbg])
    Reac522.kcst = 0.2e6 

    # Glu_mGluR1_GDPasbg -> Glu_mGluR1 + GTPasbg
    Reac523 = smodel.Reac('Reac523', vsys, lhs = [Glu_mGluR1_GDPasbg], rhs = [Glu_mGluR1,GTPasbg])
    Reac523.kcst = 0.2e6

    # ATP_actAC -> cAMP + actAC 
    Reac524 = smodel.Reac('Reac524', vsys, lhs = [ATP_actAC], rhs = [cAMP,actAC])
    Reac524.kcst = 12

    # ATP_actAC -> ATP_AC_GDPas 
    Reac525 = smodel.Reac('Reac525', vsys, lhs = [ATP_actAC], rhs = [ATP_AC_GDPas])
    Reac525.kcst = 0.3333

    # actAC -> AC_GDPas 
    Reac526 = smodel.Reac('Reac526', vsys, lhs = [actAC] , rhs = [AC_GDPas])
    Reac526.kcst = 0.3333

    # ATP_AC_GDPas -> AC_GDPas 
    Reac527 = smodel.Reac('Reac527', vsys, lhs = [ATP_AC_GDPas], rhs = [AC_GDPas])
    Reac527.kcst = 10

    # actAC + ATP <-> ATP_actAC 
    Reac528 = smodel.Reac('Reac528', vsys, lhs = [actAC,ATP], rhs = [ATP_actAC])
    Reac528.kcst = 0.2e6
    Reac529 = smodel.Reac('Reac529', vsys, lhs = [ATP_actAC], rhs = [actAC,ATP])
    Reac529.kcst = 48

    # totbasGTP + AC -> actAC
    Reac530 = smodel.Reac('Reac530', vsys, lhs = [totbasGTP, AC], rhs = [actAC])
    Reac530.kcst = 10e6
    Reac556 = smodel.Reac('Reac556', vsys, lhs = [actAC], rhs = [totbasGTP, AC])
    Reac556.kcst = 0.02

    # AC_GDPas -> AC
    Reac531 = smodel.Reac('Reac531', vsys, lhs = [AC_GDPas], rhs = [AC])
    Reac531.kcst = 0.1

    # AC_GDPai -> GDPai + AC 
    Reac532 = smodel.Reac('Reac532', vsys, lhs = [AC_GDPai], rhs = [GDPai,AC])
    Reac532.kcst = 0.1

    # inac_AC -> AC_GDPai 
    Reac533 = smodel.Reac('Reac533', vsys, lhs = [inac_AC], rhs = [AC_GDPai])
    Reac533.lcst = 0.333

    # AC + GTPai -> inac_AC
    Reac534 = smodel.Reac('Reac534', vsys, lhs = [AC, GTPai], rhs = [inac_AC])
    Reac534.kcst = 10.0e6
    Reac557 = smodel.Reac('Reac557', vsys, lhs = [inac_AC], rhs = [AC,GTPai])
    Reac557.kcst = 0.02

    # GTPai -> GDPai 
    Reac535 = smodel.Reac('Reac535', vsys, lhs = [GTPai], rhs = [GDPai])
    Reac535.kcst = 0.066

    # GTPaibg -> GDPaibg 
    Reac536 = smodel.Reac('Reac536', vsys, lhs = [GTPaibg], rhs = [GDPaibg])
    Reac536.kcst = 0.066

    # GDPai + bg -> GDPaibg 
    Reac537 = smodel.Reac('Reac537', vsys, lhs = [GDPai, bg], rhs = [GDPaibg])
    Reac537.kcst = 0.7e6
    Reac558 = smodel.Reac('Reac558', vsys, lhs = [GDPaibg], rhs = [GDPai,bg])
    Reac558.kcst = 0.0013 

    # GTPai + bg -> GTPaibg 
    Reac538 = smodel.Reac('Reac538', vsys, lhs = [GTPai, bg], rhs = [GTPaibg])
    Reac538.kcst = 0.01e6
    Reac559 = smodel.Reac('Reac559', vsys, lhs = [GTPaibg], rhs = [GTPai, bg])
    Reac559.kcst = 1.0

    # GABAbR + GDPaibg -> GABAbR_GDPaibg 
    Reac539 = smodel.Reac('Reac539', vsys, lhs = [GABAbR, GDPaibg], rhs = [GABAbR_GDPaibg])
    Reac539.kcst = 0.2e6
    Reac560 = smodel.Reac('Reac560', vsys, lhs = [GABAbR_GDPaibg], rhs = [GABAbR,GDPaibg])
    Reac560.kcst = 0.1 

    # GABA_GABAbR + GDPaibg -> GABA_GABAbR_GDPaibg 
    Reac540 = smodel.Reac('Reac540', vsys, lhs = [GABA_GABAbR, GDPaibg], rhs = [GABA_GABAbR_GDPaibg])
    Reac540.kcst = 10e6
    Reac561 = smodel.Reac('Reac561', vsys, lhs = [GABA_GABAbR_GDPaibg], rhs = [GABA_GABAbR,GDPaibg])
    Reac561.kcst = 0.1

    # GABAbR + GABA <-> GABA_GABAbR 
    Reac541 = smodel.Reac('Reac541', vsys, lhs = [GABAbR, GABA], rhs = [GABA_GABAbR])
    Reac541.kcst = 1e6
    Reac542 = smodel.Reac('Reac542', vsys, lhs = [GABA_GABAbR], rhs = [GABAbR, GABA])
    Reac542.kcst = 2

    # GABAbR_GDPaibg + GABA <-> GABA_GABAbR_GDPaibg 
    Reac543 = smodel.Reac('Reac543', vsys, lhs = [GABAbR_GDPaibg, GABA], rhs = [GABA_GABAbR_GDPaibg])
    Reac543.kcst = 1e6
    Reac544 = smodel.Reac('Reac544', vsys, lhs = [GABA_GABAbR_GDPaibg], rhs = [GABAbR_GDPaibg, GABA])
    Reac544.kcst = 2

    #GABA_GABAbR_GDPaibg -> GTPaibg + GABA_GABAbR
    Reac545 = smodel.Reac('Reac545', vsys, lhs = [GABA_GABAbR_GDPaibg], rhs = [GTPaibg,GABA_GABAbR])
    Reac545.kcst = 0.2

    # PIP2 + PLC_Gq <-> PIP2_PLC_Gq -> IP3 + DAG 
    Reac546 = smodel.Reac('Reac546', vsys, lhs = [PIP2, PLC_Gq], rhs = [PIP2_PLC_Gq])
    Reac546.kcst = 48e6
    Reac547 = smodel.Reac('Reac547', vsys, lhs = [PIP2_PLC_Gq], rhs = [PIP2, PLC_Gq])
    Reac547.kcst = 192
    Reac548 = smodel.Reac('Reac548', vsys, lhs = [PIP2_PLC_Gq], rhs = [PLC_Gq,IP3,DAG])
    Reac548.kcst = 48




    return mdl

########################################################################

# Geometric properties of the model: To change the size of the model, all volumetric compartments must be altered by the same ratio
# and all the areas must be scaled considering a spherical shape.
# Alterations in the size of the compartments will change automatically the population
# of species given in concentration (initial condition), but the species given in number of molecules must be altered manually by the same ratio
# to keep the balance among all the components of the model. 

def gen_geom():    
    g = swm.Geom()
    c = swm.Comp('vsys', g)
    c.addVolsys('vsys')
    c.vol = 2.2e-18
    
    
    return g

######################################################################


rng=srng.create('mt19937',512)
m=gen_model() 
g=gen_geom() 
tpnts=np.arange(0.0,INT,DT)
ntpnts=tpnts.shape[0]
    
# initialize arrays for storage at each time point and at each run.
Ca = numpy.zeros((NITER, ntpnts))
#CBf = numpy.zeros((NITER, ntpnts))
#CaCBf = numpy.zeros((NITER, ntpnts))
#Ca2CBf = numpy.zeros((NITER, ntpnts))
PP2A = numpy.zeros((NITER, ntpnts))
PP1 = numpy.zeros((NITER, ntpnts)) 
   
CaM = numpy.zeros((NITER, ntpnts))
CaM1Ca = numpy.zeros((NITER, ntpnts))
CaM2Ca = numpy.zeros((NITER, ntpnts))
CaM3Ca = numpy.zeros((NITER, ntpnts))
CaN = numpy.zeros((NITER, ntpnts))
CaMKII = numpy.zeros((NITER, ntpnts))
CaM3Ca_CaMKII = numpy.zeros((NITER, ntpnts))
CaM3Ca_pT286287 = numpy.zeros((NITER, ntpnts))
pT286287 = numpy.zeros((NITER, ntpnts))
pT286287_pT308306 = numpy.zeros((NITER, ntpnts))
pT308306 = numpy.zeros((NITER, ntpnts))

GC = numpy.zeros((NITER, ntpnts))
NO = numpy.zeros((NITER, ntpnts))
GC_NO = numpy.zeros((NITER, ntpnts))
GTP = numpy.zeros((NITER, ntpnts))
GTP_GC_NO = numpy.zeros((NITER, ntpnts))
cGMP = numpy.zeros((NITER, ntpnts))
GMP = numpy.zeros((NITER,ntpnts))
PDE1 = numpy.zeros((NITER, ntpnts))
pPDE1 = numpy.zeros((NITER, ntpnts))
PDE5 = numpy.zeros((NITER, ntpnts))
PDE5_cGMP = numpy.zeros((NITER, ntpnts))
PKG = numpy.zeros((NITER, ntpnts))
PKG_cGMP = numpy.zeros((NITER, ntpnts))
CaM3Ca_PDE1 = numpy.zeros((NITER, ntpnts))
CaM3Ca_pPDE1 = numpy.zeros((NITER, ntpnts))
GMP = numpy.zeros((NITER, ntpnts))
PP2A_pGsub = numpy.zeros((NITER, ntpnts))
pG = numpy.zeros((NITER, ntpnts))
G_sub = numpy.zeros((NITER, ntpnts))

CaM3Ca_pT286287_PP1 = numpy.zeros((NITER, ntpnts))
CaM3Ca_pT286287_PP2A = numpy.zeros((NITER, ntpnts))
pT286287_pT308306_PP1 = numpy.zeros((NITER, ntpnts))
pT286287_pT308306_PP2A = numpy.zeros((NITER, ntpnts))
pT286287_PP1 = numpy.zeros((NITER, ntpnts))
pT286287_PP2A = numpy.zeros((NITER, ntpnts))
pT286287_pT308306_PP1_2 = numpy.zeros((NITER, ntpnts))
pT286287_pT308306_PP2A_2 = numpy.zeros((NITER, ntpnts))
pT308306_PP1 = numpy.zeros((NITER, ntpnts))
pT308306_PP2A = numpy.zeros((NITER, ntpnts))
cGMP_CaM3Ca_pPDE1 = numpy.zeros((NITER, ntpnts))
cGMP_CaM3Ca_PDE1 = numpy.zeros((NITER, ntpnts))
cGMP_PDE1 = numpy.zeros((NITER, ntpnts))
cGMP_pPDE1 = numpy.zeros((NITER, ntpnts))
PDE1_CaMKII = numpy.zeros((NITER, ntpnts))
pPDE1_CaN = numpy.zeros((NITER, ntpnts))    
CaM3Ca_PDE1_CaMKII = numpy.zeros((NITER, ntpnts))
CaM3Ca_pPDE1_CaN = numpy.zeros((NITER, ntpnts))
pG_PP2A = numpy.zeros((NITER, ntpnts))
pG_CaN = numpy.zeros((NITER, ntpnts))
G_sub_PKG = numpy.zeros((NITER, ntpnts))
pDARPP32_PP2A = numpy.zeros((NITER, ntpnts))
PP1_pDARPP32 = numpy.zeros((NITER, ntpnts))
PP1_DARPP32 = numpy.zeros((NITER, ntpnts))
DARPP32 = numpy.zeros((NITER, ntpnts))
pDARPP32 = numpy.zeros((NITER, ntpnts))
R2C2_PKA = numpy.zeros((NITER, ntpnts))
cAMP_R2C2 = numpy.zeros((NITER, ntpnts))
cAMP2_bb_R2C2 = numpy.zeros((NITER, ntpnts))
cAMP2_ab_R2C2 = numpy.zeros((NITER, ntpnts))
cAMP2_ab_R2C = numpy.zeros((NITER, ntpnts))
cAMP3_R2C2 = numpy.zeros((NITER, ntpnts))
cAMP3_R2C = numpy.zeros((NITER, ntpnts))
cAMP4_R2C2 = numpy.zeros((NITER, ntpnts))
cAMP4_R2C = numpy.zeros((NITER, ntpnts))
cAMP4_R2 = numpy.zeros((NITER, ntpnts))
C_actPKA = numpy.zeros((NITER, ntpnts))
cAMP = numpy.zeros((NITER, ntpnts))
AMP = numpy.zeros((NITER, ntpnts))
PDE4 = numpy.zeros((NITER, ntpnts))
cAMP_PDE4 = numpy.zeros((NITER, ntpnts)) 
cAMP_PDE1 = numpy.zeros((NITER, ntpnts))
cAMP_pPDE1 = numpy.zeros((NITER, ntpnts))
cAMP_CaM3Ca_PDE1 = numpy.zeros((NITER, ntpnts))
cAMP_CaM3Ca_pPDE1  = numpy.zeros((NITER, ntpnts))
PP1_pDARPP32_PP2A  = numpy.zeros((NITER, ntpnts))
CaM3CaCaN = numpy.zeros((NITER, ntpnts))

AA = numpy.zeros((NITER, ntpnts)) 
PKC = numpy.zeros((NITER, ntpnts))
PKCAA = numpy.zeros((NITER, ntpnts))
DAG = numpy.zeros((NITER, ntpnts))
PKCDAGAA = numpy.zeros((NITER, ntpnts))
PKCCaDAGAA = numpy.zeros((NITER, ntpnts))
PKCCaDAG = numpy.zeros((NITER, ntpnts))
PKCCaAA = numpy.zeros((NITER, ntpnts))
PKCCacyto = numpy.zeros((NITER, ntpnts))
PKCCamemb = numpy.zeros((NITER, ntpnts))

Raf = numpy.zeros((NITER, ntpnts))
actRaf = numpy.zeros((NITER, ntpnts))
MAPKK = numpy.zeros((NITER, ntpnts))
MAPKK_ser = numpy.zeros((NITER, ntpnts))
act_MAPKK = numpy.zeros((NITER, ntpnts))
MAPK = numpy.zeros((NITER, ntpnts))
MAPK_tyr = numpy.zeros((NITER, ntpnts))
act_MAPK = numpy.zeros((NITER, ntpnts))
MKP_1 = numpy.zeros((NITER, ntpnts))

APC = numpy.zeros((NITER, ntpnts))
PLA2_PIP2 = numpy.zeros((NITER, ntpnts))
pPLA2_Ca = numpy.zeros((NITER, ntpnts))
PLA2_Ca = numpy.zeros((NITER, ntpnts))
PLA2 = numpy.zeros((NITER, ntpnts))
pPLA2 = numpy.zeros((NITER, ntpnts))
PLA2_PIP2_Ca = numpy.zeros((NITER, ntpnts))
DAG_PLA2_Ca = numpy.zeros((NITER, ntpnts))
PLA_PLA2 = numpy.zeros((NITER, ntpnts))
PLA_PLA2_Ca = numpy.zeros((NITER, ntpnts))
PIP2 = numpy.zeros((NITER, ntpnts))
AA_deg = numpy.zeros((NITER, ntpnts))
APC_PLA2_PIP2 = numpy.zeros((NITER, ntpnts)) 
APC_pPLA2_Ca = numpy.zeros((NITER, ntpnts))
APC_PLA2_Ca = numpy.zeros((NITER, ntpnts))
APC_pPLA2 = numpy.zeros((NITER, ntpnts))
APC_PLA2_PIP2_Ca = numpy.zeros((NITER, ntpnts))
APC_DAG_PLA2_Ca = numpy.zeros((NITER, ntpnts))
PLA2_MAPK = numpy.zeros((NITER, ntpnts))

Raf_PKC = numpy.zeros((NITER, ntpnts))
act_Raf_PP2A = numpy.zeros((NITER, ntpnts))
MAPKK_Raf = numpy.zeros((NITER, ntpnts))
MAPKK_ser_Raf = numpy.zeros((NITER, ntpnts))
act_MAPKK_PP2A = numpy.zeros((NITER, ntpnts))
MAPKK_ser_PP2A = numpy.zeros((NITER, ntpnts))
MAPK_MAPKK = numpy.zeros((NITER, ntpnts))
MAPK_tyr_MAPKK = numpy.zeros((NITER, ntpnts))
act_MAPK_MKP_1 = numpy.zeros((NITER, ntpnts))
MAPK_tyr_MKP_1 = numpy.zeros((NITER, ntpnts))


PLA2_Ca_DAG = numpy.zeros((NITER, ntpnts))
PLA2_Ca_PIP2 = numpy.zeros((NITER, ntpnts))
act_Raf = numpy.zeros((NITER, ntpnts))
act_MAPKK_ser = numpy.zeros((NITER, ntpnts))
PKC_AA = numpy.zeros((NITER, ntpnts))
PKC_Ca_AA = numpy.zeros((NITER, ntpnts))
PKC_DAG_AA = numpy.zeros((NITER, ntpnts))
PKC_Ca_DAG_AA = numpy.zeros((NITER, ntpnts))
PKC_Ca_DAG = numpy.zeros((NITER, ntpnts))
AMPAR = numpy.zeros((NITER, ntpnts))
pAMPAR = numpy.zeros((NITER, ntpnts))
PKC_AMPAR = numpy.zeros((NITER, ntpnts))
PP2A_pAMPAR = numpy.zeros((NITER, ntpnts))
GABAaR = numpy.zeros((NITER, ntpnts))
pGABAaR = numpy.zeros((NITER, ntpnts))
GABAaR_CamKII = numpy.zeros((NITER, ntpnts))
PP1_pGABAaR = numpy.zeros((NITER, ntpnts))

IP3 = numpy.zeros((NITER, ntpnts))
DAG = numpy.zeros((NITER, ntpnts))
PLC_Gq = numpy.zeros((NITER, ntpnts))
PIP2 = numpy.zeros((NITER, ntpnts))
PLC = numpy.zeros((NITER, ntpnts))
GTPaq = numpy.zeros((NITER, ntpnts))
GDPaq = numpy.zeros((NITER, ntpnts))
GTPaqbg = numpy.zeros((NITER, ntpnts))
GDPaqbg = numpy.zeros((NITER, ntpnts))
GTPas = numpy.zeros((NITER, ntpnts))
GDPas = numpy.zeros((NITER, ntpnts))
GTPasbg = numpy.zeros((NITER, ntpnts))
GDPasbg = numpy.zeros((NITER, ntpnts))
bg = numpy.zeros((NITER, ntpnts))
Glu = numpy.zeros((NITER, ntpnts))
mGluR1 = numpy.zeros((NITER, ntpnts))
Glu_mGluR1 = numpy.zeros((NITER, ntpnts))
mGluR1_GDPaqbg = numpy.zeros((NITER, ntpnts))
mGluR1_GDPasbg = numpy.zeros((NITER, ntpnts))
Glu_mGluR1_GDPaqbg = numpy.zeros((NITER, ntpnts))
Glu_mGluR1_GDPasbg = numpy.zeros((NITER, ntpnts))
GABA = numpy.zeros((NITER, ntpnts))
GABAbR = numpy.zeros((NITER, ntpnts))
GABA_GABAbR = numpy.zeros((NITER, ntpnts))
GABAbR_GDPaibg = numpy.zeros((NITER, ntpnts))
GABA_GABAbR_GDPaibg = numpy.zeros((NITER, ntpnts))
actGi = numpy.zeros((NITER, ntpnts))
Gi = numpy.zeros((NITER, ntpnts))
bc = numpy.zeros((NITER, ntpnts))
GTPai = numpy.zeros((NITER, ntpnts))
GDPai = numpy.zeros((NITER, ntpnts))
AC = numpy.zeros((NITER, ntpnts))
inac_AC = numpy.zeros((NITER, ntpnts))
AC_GDPai = numpy.zeros((NITER, ntpnts))
actAC = numpy.zeros((NITER, ntpnts))
AC_GDPas = numpy.zeros((NITER, ntpnts))
ATP = numpy.zeros((NITER, ntpnts))
ATP_actAC = numpy.zeros((NITER, ntpnts))
ATP_AC_GDPas = numpy.zeros((NITER, ntpnts))
deg = numpy.zeros((NITER, ntpnts))
GTPaibg = numpy.zeros((NITER, ntpnts))
GDPaibg = numpy.zeros((NITER, ntpnts))
PIP2_PLC_Gq = numpy.zeros((NITER, ntpnts))
pG_CaM3CaCaN = numpy.zeros((NITER, ntpnts))
totPKC = numpy.zeros((NITER, ntpnts))
actCaMKII = numpy.zeros((NITER, ntpnts))
GMP = numpy.zeros((NITER, ntpnts))
pPDE1 = numpy.zeros((NITER, ntpnts))

#ica=gaussian_ica(tpnts)
    
sim = swmdirect.Wmdirect(m, g, rng)
    
    
for j in arange(NITER): 
    print "Run number {0}".format(j)
    rng.initialize(datetime.datetime.now().microsecond) 
    sim.reset() 
    
    sim.setCompConc('vsys','Glu',0.001e-6)
    sim.setCompClamped('vsys','Glu', True)
    sim.setCompConc('vsys','GABA',0.01e-6)
    sim.setCompClamped('vsys','GABA',True)
    sim.setCompConc('vsys','NO',0.05e-6)
    sim.setCompClamped('vsys','NO',True)

    sim.setCompConc('vsys','CaMKII',Kin*1e-6)
    sim.setCompConc('vsys','CaM',60e-6)
    sim.setCompConc('vsys','CaN',10e-6)
    
    
    sim.setCompConc('vsys','GABAaR',1e-6)
    sim.setCompConc('vsys','DARPP32',0.7e-6)
    sim.setCompConc('vsys','R2C2_PKA',0.25e-6)
    sim.setCompConc('vsys','MAPK',0.2e-6)
    sim.setCompConc('vsys','MAPKK',0.1e-6)
    
    
    sim.setCompConc('vsys','Raf',0.2e-6)
    sim.setCompConc('vsys','MKP_1',0.005e-6)
    sim.setCompConc('vsys','GABAbR',0.5e-6)  
    
    sim.setCompConc('vsys','GDPaibg',1.5e-6)
    sim.setCompConc('vsys','AC',0.02e-6)
    sim.setCompConc('vsys','AMPAR',1e-6)
    sim.setCompConc('vsys','PDE5',0.6e-6)
    sim.setCompConc('vsys','PDE1',0.6e-6)
    sim.setCompConc('vsys','PDE4',0.6e-6)
    sim.setCompConc('vsys','GC',0.02e-6)

    sim.setCompConc('vsys','PKG',0.1e-6)
    sim.setCompConc('vsys','PLA2',0.4e-6)
    sim.setCompConc('vsys','PIP2',3e-6)
    sim.setCompClamped('vsys','PIP2',True)
    sim.setCompConc('vsys','G_sub',0.7e-6)
 
    sim.setCompConc('vsys','PLC',0.2e-6)
    sim.setCompConc('vsys','cAMP', 0.15e-6)
    sim.setCompConc('vsys','ATP',2000e-6)
    sim.setCompClamped('vsys','ATP',True)
    sim.setCompConc('vsys','AMP',1000e-6)
    sim.setCompClamped('vsys','AMP',True)

    sim.setCompConc('vsys','GTP',100e-6)
    sim.setCompClamped('vsys','GTP',True)
    sim.setCompConc('vsys','GMP', 0.1e-6)
    sim.setCompClamped('vsys','GMP',True)
    sim.setCompConc('vsys','cGMP', 0.02e-6)

    sim.setCompConc('vsys','APC',3e-6)
    sim.setCompClamped('vsys','APC',True)
    
    sim.setCompConc('vsys','mGluR1',0.5e-6)
    sim.setCompConc('vsys','GDPasbg',1.5e-6)
    sim.setCompConc('vsys','GDPaqbg',1.5e-6)
    sim.setCompConc('vsys','deg',0)
    sim.setCompClamped('vsys','deg',True)
    sim.setCompConc('vsys','AA_deg',0)
    sim.setCompClamped('vsys','AA_deg',True)






    for i in range(ntpnts):
        if (tpnts[i] < 100) : sim.setCompConc('vsys','Ca',0.1e-6)
        if ((tpnts[i] > 100) and (tpnts[i] < 110)): sim.setCompConc('vsys','Ca',2e-6)
        #if ((tpnts[i] > 600) and (tpnts[i] < 605)): sim.setCompConc('vsys','Ca',0.1e-6)
        #if ((tpnts[i] > 605) and (tpnts[i] < 620)): sim.setCompConc('vsys','Ca',0.8e-6)
        #if ((tpnts[i] > 520) and (tpnts[i] < 623)): sim.setCompConc('vsys','Ca',0.1e-6)
        #if ((tpnts[i] > 523) and (tpnts[i] < 630)): sim.setCompConc('vsys','Ca',0.8e-6)
        #if ((tpnts[i] > 560) and (tpnts[i] < 631)): sim.setCompConc('vsys','Ca',0.8e-6)
        #if ((tpnts[i] > 900) and (tpnts[i] < 1200)): sim.setCompConc('vsys','Ca',1.5e-6)
        #if ((tpnts[i] > 900) and (tpnts[i] < 1200)): sim.setCompConc('vsys','Ca',1.5e-6)
        #if ((tpnts[i] > 900) and (tpnts[i] < 1200)): sim.setCompConc('vsys','Ca',1.5e-6)
        if (tpnts[i] > 110) : sim.setCompConc('vsys','Ca',0.1e-6)
        sim.setCompConc('vsys','totPKC',sim.getCompConc('vsys','PKC_AA') + sim.getCompConc('vsys','PKC_Ca_DAG_AA') + sim.getCompConc('vsys','PKC_Ca_DAG') + sim.getCompConc('vsys','PKC_Ca_AA') + sim.getCompConc('vsys','PKCCamemb') + sim.getCompConc('vsys','PKC_DAG_AA'))
        sim.setCompConc('vsys','totbasGTP', 0.0012e-6 + sim.getCompConc('vsys','GTPas'))
        sim.setCompConc('vsys','calc_3_1', sim.getCompConc('vsys','CaM3Ca_pT286287') + sim.getCompConc('vsys','pT286287') + sim.getCompConc('vsys','CaM3Ca_CaMKII') + sim.getCompConc('vsys','pT286287_pT308306'))
        calc_3_4 =  sim.getCompConc('vsys','calc_3_1') + sim.getCompConc('vsys','CaMKII') + sim.getCompConc('vsys','pT308306') + sim.getCompConc('vsys','pT308306_PP1') + sim.getCompConc('vsys','pT286287_PP1') + sim.getCompConc('vsys','pT286287_pT308306_PP2A_2') + sim.getCompConc('vsys','pT286287_pT308306_PP2A') + sim.getCompConc('vsys','CaM3Ca_pT286287_PP1') + sim.getCompConc('vsys','CaM3Ca_pT286287_PP2A') + sim.getCompConc('vsys','pT286287_PP2A') + sim.getCompConc('vsys','pT286287_pT308306_PP1') + sim.getCompConc('vsys','pT286287_pT308306_PP1_2') + sim.getCompConc('vsys','pT308306_PP2A')
        sim.setCompConc('vsys','calc_3_3', sim.getCompConc('vsys','calc_3_1')/calc_3_4)
        #calc_3_3 =  sim.getCompConc('vsys','calc_3_1')/calc_3_4

        sim.run(tpnts[i]) 

        print "percent done",(tpnts[i]/INT*100),j 
        #a = sim.getCompCount('vsys','PP2A') 
        #b = sim.getCompCount('vsys','PKC_AA')
        #print calc_3_1, calc_3_4, calc_3_3 
            

        Ca[j,i] = sim.getCompConc('vsys','Ca')
        #CaCBf[j,i] = sim.getCompConc('vsys', 'CaCBf')
        #Ca2CBf[j,i] = sim.getCompConc('vsys', 'Ca2CBf')
        CaMKII[j,i] = sim.getCompConc('vsys','CaMKII')
        CaM1Ca[j,i] = sim.getCompConc('vsys','CaM1Ca')
        CaM2Ca[j,i] = sim.getCompConc('vsys','CaM2Ca')
        CaM3Ca[j,i] = sim.getCompConc('vsys','CaM3Ca')
        PDE1[j,i] = sim.getCompConc('vsys','PDE1')
        pG[j,i] = sim.getCompConc('vsys','pG')    
        CaM3Ca_pT286287[j,i] = sim.getCompConc('vsys', 'CaM3Ca_pT286287')
        PP2A[j,i] = sim.getCompConc('vsys', 'PP2A')
        PP2A_pGsub[j,i] = sim.getCompConc('vsys','PP2A_pGsub')
        pT286287_PP2A[j,i] = sim.getCompConc('vsys','pT286287_PP2A')    
        pT308306_PP2A[j,i] = sim.getCompConc('vsys','pT308306_PP2A')
        pDARPP32_PP2A[j,i] = sim.getCompConc('vsys','pDARPP32_PP2A')
        pG_PP2A[j,i] = sim.getCompConc('vsys','pG_PP2A')
        PP1_pDARPP32_PP2A[j,i] = sim.getCompConc('vsys','PP1_pDARPP32_PP2A')
        pT286287_pT308306_PP2A[j,i] = sim.getCompConc('vsys','pT286287_pT308306_PP2A')
        CaM3Ca_pT286287_PP2A[j,i] = sim.getCompConc('vsys','CaM3Ca_pT286287_PP2A')
        pT286287_pT308306_PP2A_2[j,i] = sim.getCompConc('vsys','pT286287_pT308306_PP2A_2')
        C_actPKA[j,i] = sim.getCompConc('vsys','C_actPKA')
        PDE1[j,i] = sim.getCompConc('vsys','PDE1')  
        pPDE1[j,i] = sim.getCompConc('vsys','pPDE1')    
        PDE1_CaMKII[j,i] = sim.getCompConc('vsys','PDE1_CaMKII')
        cAMP_PDE1[j,i] = sim.getCompConc('vsys','cAMP_PDE1')
        cGMP_PDE1[j,i] = sim.getCompConc('vsys','cGMP_PDE1')
        CaM3Ca_PDE1[j,i] = sim.getCompConc('vsys','CaM3Ca_PDE1')
        CaM3Ca_pPDE1[j,i] = sim.getCompConc('vsys','CaM3Ca_pPDE1')
        CaM3Ca_PDE1_CaMKII[j,i] = sim.getCompConc('vsys','CaM3Ca_PDE1_CaMKII')
        cAMP_CaM3Ca_pPDE1[j,i] = sim.getCompConc('vsys','cAMP_CaM3Ca_pPDE1')
        cAMP_CaM3Ca_PDE1[j,i] = sim.getCompConc('vsys','cAMP_CaM3Ca_PDE1')   
        CaM3Ca_pPDE1[j,i] = sim.getCompConc('vsys','CaM3Ca_pPDE1')
        CaM3Ca[j,i] = sim.getCompConc('vsys','CaM3Ca')
        cAMP[j,i] = sim.getCompConc('vsys','cAMP')
        cGMP[j,i] = sim.getCompConc('vsys','cGMP')
        PKG[j,i] = sim.getCompConc('vsys','PKG')
        pDARPP32[j,i] = sim.getCompConc('vsys','pDARPP32')
        DARPP32[j,i] = sim.getCompConc('vsys','DARPP32')
        PP1_pDARPP32[j,i] = sim.getCompConc('vsys','PP1_pDARPP32')
        PP1_DARPP32[j,i] = sim.getCompConc('vsys','PP1_DARPP32')
        CaN[j,i] = sim.getCompConc('vsys','CaN')
        PP1[j,i] = sim.getCompConc('vsys','PP1')
        CaM3CaCaN[j,i] = sim.getCompConc('vsys','CaM3CaCaN')
        #totPKC[j,i] = sim.getCompCount('vsys','totPKC')
        AMPAR[j,i] = sim.getCompConc('vsys','AMPAR')
        C_actPKA[j,i] = sim.getCompConc('vsys','C_actPKA')
        PKC_AA[j,i] = sim.getCompConc('vsys','PKC_AA')
        PDE4[j,i] = sim.getCompConc('vsys','PDE4')
        AA[j,i] = sim.getCompConc('vsys','AA')
        PLA2[j,i] = sim.getCompConc('vsys','PLA2')
        PP1_DARPP32[j,i] = sim.getCompConc('vsys','PP1_DARPP32')
        G_sub[j,i] = sim.getCompConc('vsys','G_sub')
        CaN[j,i] = sim.getCompConc('vsys','CaN')
        PKG[j,i] = sim.getCompConc('vsys','PKG')
        cAMP_R2C2[j,i] = sim.getCompConc('vsys','cAMP_R2C2')
        cAMP4_R2C2[j,i] = sim.getCompConc('vsys','cAMP4_R2C2')
        GDPaibg[j,i] = sim.getCompConc('vsys','GDPaibg')
        GTPaibg[j,i] = sim.getCompConc('vsys','GTPaibg')
        AC[j,i] = sim.getCompConc('vsys','AC')
        Raf[j,i] = sim.getCompConc('vsys','Raf')
        PKC[j,i] = sim.getCompConc('vsys','PKC')
        PLC[j,i] = sim.getCompConc('vsys','PLC')
        actAC[j,i] = sim.getCompConc('vsys','actAC')
        NO[j,i] = sim.getCompConc('vsys','NO')
        GC[j,i] = sim.getCompConc('vsys','GC')
        GC_NO[j,i] = sim.getCompConc('vsys','GC_NO')
        R2C2_PKA[j,i] = sim.getCompConc('vsys','R2C2_PKA')
        PP2A_pAMPAR[j,i] = sim.getCompConc('vsys','PP2A_pAMPAR')
        totPKC[j,i] = sim.getCompConc('vsys','totPKC')
        actCaMKII[j,i] = sim.getCompConc('vsys','calc_3_1') + sim.getCompConc('vsys','GABAaR_CaMKII') + sim.getCompConc('vsys','PDE1_CaMKII') + sim.getCompConc('vsys','CaM3Ca_CaMKII')
        actAC[j,i] = sim.getCompConc('vsys','actAC')
        ATP_actAC[j,i] = sim.getCompConc('vsys','ATP_actAC')    
        CaMKII[j,i] = sim.getCompConc('vsys','CaMKII')
        CaM3Ca_CaMKII[j,i] = sim.getCompConc('vsys','CaM3Ca_CaMKII')
        CaM3Ca_pT286287[j,i] = sim.getCompConc('vsys','CaM3Ca_pT286287')
        pT286287[j,i] = sim.getCompConc('vsys','pT286287')
        pT308306[j,i] = sim.getCompConc('vsys','pT308306')
        #sim.setCompReacK('vsys', 'Cainflux', ica[i]) # changes reaction constant to be ...
    
####################################################################################
#------------------------------------------------------------------------------------------------------------
#------------------------------------------------------------------------------------------------------------
CaM3Ca_PDE1mean = mean(CaM3Ca_PDE1,axis = 0)
filename3 = "actPDE1" + str(Kin) + "CaMKII.txt"
savetxt(filename3,CaM3Ca_PDE1mean)

#-------------------------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------
AAmean = mean(AA, axis = 0)
filename25 = "AA" + str(Kin) + "CaMKII.txt"
savetxt(filename25,AAmean)
close()
#--------------------------------------------------------------------------------------------------------------


AMPARmean = mean(AMPAR, axis = 0)
filename58 = "AMPAR" + str(Kin) + "CaMKII.txt"
savetxt(filename58,AMPARmean)
close()

totPKCmean = mean(totPKC, axis = 0)
filename79 = "totPKC" + str(Kin) + "CaMKII.txt"
savetxt(filename79,totPKCmean)
close()

actCaMKIImean = mean(actCaMKII, axis = 0)
filename80 = "actCaMKII" + str(Kin) + "CaMKII.txt"
savetxt(filename80,actCaMKIImean)
close()

PP2A_mean = mean(PP2A, axis = 0)
#PP2A_pGsub_mean = mean(PP2A_pGsub, axis = 0)
#pT308306_PP2A_mean = mean(pT308306_PP2A, axis = 0)
#pT286287_PP2A_mean = mean(pT286287_PP2A, axis = 0)
#pDARPP32_PP2A_mean = mean(pDARPP32_PP2A, axis = 0)
#pG_sub_PP2A_mean = mean(pG_sub_PP2A, axis = 0)
#PP1_pDARPP32_PP2A_mean = mean(PP1_pDARPP32_PP2A, axis = 0)
#pT286287_pT308306_PP2A_mean = mean(pT286287_pT308306_PP2A, axis = 0)
#CaM3Ca_pT286287_PP2A_mean = mean(CaM3Ca_pT286287_PP2A, axis = 0)
#pT286287_pT308306_PP2A_2_mean = mean(pT286287_pT308306_PP2A_2, axis = 0)

#PP2AMean = PP2A_pGsub_mean + pT308306_PP2A_mean + pT286287_PP2A_mean + pDARPP32_PP2A_mean + pG_sub_PP2A_mean + PP1_pDARPP32_PP2A_mean + pT286287_pT308306_PP2A_mean + CaM3Ca_pT286287_PP2A_mean + pT286287_pT308306_PP2A_2_mean
PP2AMean = PP2A_mean
plot(linspace(0,INT-tinit,(INT-tinit)/DT), PP2AMean[tinit/DT-1:INT/DT-1], 'g')
xlabel('Time (s)')
ylabel('PP2A(#)')
filename2 = "PP2A_" + str(Kin) + "CaMKII"
savefig(filename2) 
close()  
#--------------------------------------------------------------------------------------------------------------
CaM3Ca_pPDE1mean = mean(CaM3Ca_pPDE1,axis = 0)
CaM3Ca_PDE1mean = mean(CaM3Ca_PDE1,axis = 0)
PDE1mean = mean(PDE1, axis = 0)
PDE1_mean =  CaM3Ca_PDE1mean 
plot(linspace(0,INT-tinit,(INT-tinit)/DT), CaM3Ca_PDE1mean[tinit/DT-1:INT/DT-1], 'g')
xlabel('Time (s)')
ylabel('CaM3Ca_PDE1mean')
filename3 = "CaM3Ca_PDE1mean" + str(Kin) + "CaMKII"
savefig(filename3)   
close()
#--------------------------------------------------------------------------------------------------------------


plot(linspace(0,INT-tinit,(INT-tinit)/DT),PDE1mean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('PDE1')
filename5 = "PDE1" + str(Kin) + "CaMKII"
savefig(filename5)
close()
#--------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------

PP2A_pGsubmean = mean(PP2A_pGsub, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),PP2A_pGsubmean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('PP2A+pGsub')
filename9 = "PP2A_pGsub" + str(Kin) + "CaMKII"
savefig(filename9)
close()
#--------------------------------------------------------------------------------------------------------------

cAMPmean = mean(cAMP, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),cAMPmean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('cAMP')
filename10 = "cAMP" + str(Kin) + "CaMKII"
savefig(filename10)
close()
#--------------------------------------------------------------------------------------------------------------
cGMPmean = mean(cGMP, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),cGMPmean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('cGMP')
filename29 = "cGMP" + str(Kin) + "CaMKII"
savefig(filename29)
close()
#--------------------------------------------------------------------------------------------------------------

CaM3CaCaNmean = mean(CaM3CaCaN, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),CaM3CaCaNmean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('CaM3CaCaN')
filename11 = "CaM3CaCaN" + str(Kin) + "CaMKII"
savefig(filename11)
close()
#--------------------------------------------------------------------------------------------------------------
CaM1CaMean = mean(CaM1Ca,axis =0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT), CaM1CaMean[tinit/DT-1:INT/DT-1], 'g')
xlabel('Time (s)')
ylabel('CaM1Ca')
filename1 = "CaM1Ca" + str(Kin) + "CaMKII"
savefig(filename1) 
close()  
#--------------------------------------------------------------------------------------------------------------

PKC_AAMean = mean(PKC_AA, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT), PKC_AAMean[tinit/DT-1:INT/DT-1], 'g')
xlabel('Time (s)')
ylabel('PKC_AA')
filename30 = "PKC_AA" + str(Kin) + "CaMKII"
savefig(filename30) 
close()  

PDE4Mean = mean(PDE4, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT), PDE4Mean[tinit/DT-1:INT/DT-1], 'g')
xlabel('Time (s)')
ylabel('PDE4')
filename31 = "PDE4" + str(Kin) + "CaMKII"
savefig(filename31) 
close()  


PP1mean = mean(PP1, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),PP1mean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('PP1')
filename15 = "PP1" + str(Kin) + "CaMKII"
savefig(filename15)
close()
#--------------------------------------------------------------------------------------------------------------
AAmean = mean(AA, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),AAmean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('AA')
filename25 = "AA" + str(Kin) + "PDE1_CaMKII"
savefig(filename25)
close()
#--------------------------------------------------------------------------------------------------------------

PP1_pDARPP32mean = mean(PP1_pDARPP32, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),PP1_pDARPP32mean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('PP1_pDARPP32')
filename16 = "PP1_pDARPP32" + str(Kin) + "CaMKII"
savefig(filename16)
close()
#--------------------------------------------------------------------------------------------------------------

Camean = mean(Ca, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),Camean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('Ca')
filename17 = "Ca" + str(Kin) + "CaMKII"
savefig(filename17)
close()

C_actPKAmean = mean(C_actPKA, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),C_actPKAmean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('C_actPKA')
filename18 = "C_actPKA" + str(Kin) + "CaMKII"
savefig(filename18)
close()

PLA2mean = mean(PLA2, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),PLA2mean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('PLA2')
filename18 = "PLA2" + str(Kin) + "CaMKII"
savefig(filename18)
close()

AMPARmean = mean(AMPAR, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),AMPARmean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('AMPAR')
filename58 = "AMPAR" + str(Kin) + "CaMKII"
savefig(filename58)
close()

PKGmean = mean(PKG, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),PKGmean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('PKG')
filename61 = "PKG" + str(Kin) + "CaMKII"
savefig(filename61)
close()

G_submean = mean(G_sub, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),G_submean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('G_sub')
filename62 = "G_sub" + str(Kin) + "CaMKII"
savefig(filename62)
close()

PP1_DARPP32mean = mean(PP1_DARPP32, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),PP1_DARPP32mean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('PP1_DARPP32')
filename63 = "PP1_DARPP32" + str(Kin) + "CaMKII"
savefig(filename63)
close()

CaNmean = mean(CaN, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),CaNmean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('CaN')
filename64 = "CaN" + str(Kin) + "CaMKII"
savefig(filename64)
close()

ATP_actACmean = mean(ATP_actAC, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),ATP_actACmean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('ATP_actAC')
filename65 = "ATP_actAC" + str(Kin) + "CaMKII"
savefig(filename65)
close()

cAMP_R2C2mean = mean(cAMP_R2C2, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),cAMP_R2C2mean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('cAMP_R2C2')
filename66 = "cAMP_R2C2" + str(Kin) + "CaMKII"
savefig(filename66)
close()

cAMP4_R2C2mean = mean(cAMP4_R2C2, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),cAMP4_R2C2mean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('cAMP4_R2C2')
filename67 = "cAMP4_R2C2" + str(Kin) + "CaMKII"
savefig(filename67)
close()

Gimean = mean(GDPaibg, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),Gimean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('Gi')
filename68 = "Gi" + str(Kin) + "CaMKII"
savefig(filename68)
close()

GTPaibgmean = mean(GTPaibg, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),GTPaibgmean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('GTPaibg')
filename69 = "GTPaibg" + str(Kin) + "CaMKII"
savefig(filename69)
close()

ACmean = mean(AC, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),ACmean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('AC')
filename70 = "AC" + str(Kin) + "CaMKII"
savefig(filename70)
close()

Rafmean = mean(Raf, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),Rafmean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('Raf')
filename71 = "Raf" + str(Kin) + "CaMKII"
savefig(filename71)
close()

PKCmean = mean(PKC, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),PKCmean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('PKC')
filename72 = "PKC" + str(Kin) + "CaMKII"
savefig(filename72)
close()

PLCmean = mean(PLC, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),PLCmean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('PLC')
filename73 = "PLC" + str(Kin) + "CaMKII"
savefig(filename73)
close()

actACmean = mean(actAC, axis = 0)
PKCmean = mean(PKC, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),actACmean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('actAC')
filename74 = "actAC" + str(Kin) + "CaMKII"
savefig(filename74)
close()

GCmean = mean(GC, axis = 0)

plot(linspace(0,INT-tinit,(INT-tinit)/DT),GCmean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('GC')
filename75 = "GC" + str(Kin) + "CaMKII"
savefig(filename75)
close()

NOmean = mean(NO, axis = 0)

plot(linspace(0,INT-tinit,(INT-tinit)/DT),NOmean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('NO')
filename76 = "NO" + str(Kin) + "CaMKII"
savefig(filename76)
close()

GC_NOmean = mean(GC_NO, axis = 0)

plot(linspace(0,INT-tinit,(INT-tinit)/DT),GC_NOmean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('GC_NO')
filename77 = "GC_NO" + str(Kin) + "CaMKII"
savefig(filename77)
close()

R2C2_PKAmean = mean(R2C2_PKA, axis = 0)

plot(linspace(0,INT-tinit,(INT-tinit)/DT),R2C2_PKAmean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('aR2C2_PKA')
filename78 = "R2C2_PKA" + str(Kin) + "CaMKII"
savefig(filename78)
close()

GMPmean = mean(GMP, axis = 0)

plot(linspace(0,INT-tinit,(INT-tinit)/DT),R2C2_PKAmean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('aR2C2_PKA')
filename79 = "R2C2_PKA" + str(Kin) + "CaMKII"
savefig(filename79)
close()

actACmean = mean(actAC, axis = 0)

plot(linspace(0,INT-tinit,(INT-tinit)/DT),actACmean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('actAC')
filename80 = "actAC" + str(Kin) + "CaMKII"
savefig(filename80)
close()

ATP_actACmean = mean(ATP_actAC, axis = 0)

plot(linspace(0,INT-tinit,(INT-tinit)/DT),ATP_actACmean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('ATP_actAC')
filename81 = "ATP_actAC" + str(Kin) + "CaMKII"
savefig(filename81)
close()

pPDE1mean = mean(pPDE1, axis = 0)

plot(linspace(0,INT-tinit,(INT-tinit)/DT),pPDE1mean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('pPDE1')
filename82 = "pPDE1" + str(Kin) + "CaMKII"
savefig(filename82)
close()

CaMKIImean = mean(CaMKII, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),CaMKIImean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('CaMKII')
filename83 = "CaMKII" + str(Kin) + "CaMKII"
savefig(filename83)
close()

CaM3Ca_pT286287mean = mean(CaM3Ca_pT286287, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),CaM3Ca_pT286287mean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('CaM3Ca_pT286287')
filename84 = "CaM3Ca_pT286287" + str(Kin) + "CaMKII"
savefig(filename84)
close()

pT286287mean = mean(pT286287, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),pT286287mean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('pT286287')
filename85 = "pT286287" + str(Kin) + "CaMKII"
savefig(filename85)
close()

pT286287_pT308306mean = mean(pT286287_pT308306, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),pT286287_pT308306mean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('pT286287_pT308306')
filename86 = "pT286287_pT308306" + str(Kin) + "CaMKII"
savefig(filename86)
close()

pT308306mean = mean(pT308306, axis = 0)
plot(linspace(0,INT-tinit,(INT-tinit)/DT),pT308306mean[tinit/DT-1:INT/DT-1]*1e6,'k')
xlabel('Time (s)')
ylabel('pT308306')
filename87 = "pT308306" + str(Kin) + "CaMKII"
savefig(filename87)
close()

