
import datetime
import steps.model as smodel
import math
import sys
import numpy 
import numpy as np
from numpy import mean
import steps.solver as swmdirect
import steps.geom as swm
import steps.rng as srng
from pylab import*
import os
import pickle

a = 0
#calc_3_3 = 0
#calc_3_1 = 0
calc_3_4 = 0
#totPKC = 0
DT = 0.05 # time step
INT = 2000 # final time (s) simulated
NITER = 1 # number of runs used to calculate the mean
tinit = 600 # initial time that will be discharged. The initial 10 minutes of all simulations should be discharged to allow the model to reach equilibrium.

# Avogadro constant
Na = 6.02214129e23
Kin = input("Calcium Kinase input")
type (Kin)
########################################################################

# Ca2+ pulse. IMPORTANT: the duration and amplitude of the pulse should be checked directly in the Ca2+ concentration
# The changes in [Ca2+] generated by the pulses are highly stochastic
# altering max_molar alters the maximum molar concentration per second injection (M/s) 
# cntr defines the time the pulse is at maximum (s)
# FW100M defines the full-width 100th maximum of the Gaussian (s)

#def gaussian_ica(t,max_molar=100.0e-6/0.05,cntr=1000.0,FW100M=120):
    #c = FW100M/(2*math.sqrt(2*math.log(100)))
    #return max_molar*np.exp(-(((t-cntr)**2)/(2*c**2)))

######################################################################## 

def gen_model(): 
    mdl=smodel.Model() 
    
    Ca = smodel.Spec('Ca', mdl)
    #CBf = smodel.Spec('CBf',mdl)
    #CaCBf = smodel.Spec('CaCBf',mdl)
    #Ca2CBf = smodel.Spec('Ca2CBf',mdl)
    PP2A = smodel.Spec('PP2A', mdl)                        
    PP1 = smodel.Spec('PP1', mdl)
    

    CaM = smodel.Spec('CaM',mdl)
    CaM1Ca = smodel.Spec('CaM1Ca',mdl)
    CaM2Ca = smodel.Spec('CaM2Ca',mdl)
    CaM3Ca = smodel.Spec('CaM3Ca',mdl)
    CaN = smodel.Spec('CaN',mdl)
    CaM3CaCaN = smodel.Spec('CaM3CaCaN',mdl)
    CaMKII = smodel.Spec('CaMKII',mdl)
    CaM3Ca_CaMKII = smodel.Spec('CaM3Ca_CaMKII',mdl)
    CaM3Ca_pT286287 = smodel.Spec('CaM3Ca_pT286287',mdl)
    pT286287 = smodel.Spec('pT286287',mdl)
    pT286287_pT308306 = smodel.Spec('pT286287_pT308306',mdl)
    pT308306 = smodel.Spec('pT308306',mdl)

    GC = smodel.Spec('GC',mdl)
    NO = smodel.Spec('NO',mdl)
    GC_NO = smodel.Spec('GC_NO',mdl)
    GTP = smodel.Spec('GTP',mdl)
    GTP_GC_NO = smodel.Spec('GTP_GC_NO',mdl)
    cGMP = smodel.Spec('cGMP',mdl)
    GMP = smodel.Spec('GMP',mdl)
    PDE1 = smodel.Spec('PDE1',mdl)
    pPDE1 = smodel.Spec('pPDE1',mdl)
    PDE5 = smodel.Spec('PDE5',mdl)
    PDE5_cGMP = smodel.Spec('PDE5_cGMP',mdl)
    PKG = smodel.Spec('PKG',mdl)
    PKG_cGMP = smodel.Spec('PKG_cGMP',mdl)
    PP2A_pGsub = smodel.Spec('PP2A_pGsub',mdl)
    pG = smodel.Spec('pG',mdl)
    G_sub = smodel.Spec('G_sub',mdl)

    CaM3Ca_pT286287_PP1 = smodel.Spec('CaM3Ca_pT286287_PP1',mdl)
    CaM3Ca_pT286287_PP2A = smodel.Spec('CaM3Ca_pT286287_PP2A',mdl)
    pT286287_pT308306_PP1 = smodel.Spec('pT286287_pT308306_PP1',mdl)
    pT286287_pT308306_PP2A = smodel.Spec('pT286287_pT308306_PP2A',mdl)
    pT286287_PP1 = smodel.Spec('pT286287_PP1',mdl)
    pT286287_PP2A = smodel.Spec('pT286287_PP2A',mdl)
    pT286287_pT308306_PP1_2 = smodel.Spec('pT286287_pT308306_PP1_2',mdl)
    pT286287_pT308306_PP2A_2 = smodel.Spec('pT286287_pT308306_PP2A_2',mdl)
    pT308306_PP1 = smodel.Spec('pT308306_PP1',mdl)
    pT308306_PP2A = smodel.Spec('pT308306_PP2A',mdl)
    cGMP_CaM3Ca_pPDE1 = smodel.Spec('cGMP_CaM3Ca_pPDE1',mdl)
    cGMP_CaM3Ca_PDE1 = smodel.Spec('cGMP_CaM3Ca_PDE1',mdl)
    cGMP_PDE1 = smodel.Spec('cGMP_PDE1',mdl)
    cGMP_PDE5 = smodel.Spec('cGMP_PDE5',mdl)
    cGMP_pPDE1 = smodel.Spec('cGMP_pPDE1',mdl)
    PDE1_CaMKII = smodel.Spec('PDE1_CaMKII',mdl)
    pPDE1_CaN = smodel.Spec('pPDE1_CaN',mdl)
    CaM3Ca_PDE1_CaMKII = smodel.Spec('CaM3Ca_PDE1_CaMKII',mdl)
    CaM3Ca_pPDE1_CaN = smodel.Spec('CaM3Ca_pPDE1_CaN',mdl)
    pG_PP2A = smodel.Spec('pG_PP2A',mdl)
    pG_CaN = smodel.Spec('pG_CaN',mdl)
    G_sub_PKG = smodel.Spec('G_sub_PKG',mdl)
    CaM3Ca_PDE1 = smodel.Spec('CaM3Ca_PDE1',mdl)
    CaM3Ca_pPDE1 = smodel.Spec('CaM3Ca_pPDE1',mdl)

    PP1_pDARPP32 = smodel.Spec('PP1_pDARPP32',mdl)
    PP1_DARPP32 = smodel.Spec('PP1_DARPP32',mdl)
    DARPP32 = smodel.Spec('DARPP32',mdl)
    pDARPP32 = smodel.Spec('pDARPP32',mdl)
    R2C2_PKA = smodel.Spec('R2C2_PKA',mdl)
    cAMP_R2C2 = smodel.Spec('cAMP_R2C2',mdl)
    cAMP2_bb_R2C2 = smodel.Spec('cAMP2_bb_R2C2',mdl)
    cAMP2_ab_R2C2 = smodel.Spec('cAMP2_ab_R2C2',mdl)
    cAMP2_ab_R2C = smodel.Spec('cAMP2_ab_R2C',mdl)
    cAMP3_R2C2 = smodel.Spec('cAMP3_R2C2',mdl)
    cAMP3_R2C = smodel.Spec('cAMP3_R2C',mdl)
    cAMP4_R2C2 = smodel.Spec('cAMP4_R2C2',mdl)
    cAMP4_R2C = smodel.Spec('cAMP4_R2C',mdl)
    cAMP4_R2 = smodel.Spec('cAMP4_R2',mdl)
    C_actPKA = smodel.Spec('C_actPKA',mdl)
    cAMP = smodel.Spec('cAMP',mdl)
    AMP = smodel.Spec('AMP',mdl)
    PDE4 = smodel.Spec('PDE4',mdl)
    cAMP_pPDE1 = smodel.Spec('cAMP_pPDE1',mdl)
    cAMP_PDE1 = smodel.Spec('cAMP_PDE1',mdl)
    cAMP_CaM3Ca_PDE1 = smodel.Spec('cAMP_CaM3Ca_PDE1',mdl)
    cAMP_CaM3Ca_pPDE1 = smodel.Spec('cAMP_CaM3Ca_pPDE1',mdl)
    cAMP_PDE4 = smodel.Spec('cAMP_PDE4',mdl)

    PP1_pDARPP32_PP2A = smodel.Spec('PP1_pDARPP32_PP2A',mdl)
    PP1_pDARPP32_CaN = smodel.Spec('PP1_pDARPP32_CaN',mdl)
    PP1_DARPP32_C_actPKA = smodel.Spec('PP1_DARPP32_C_actPKA',mdl)
    pDARPP32_PP2A = smodel.Spec('pDARPP32_PP2A',mdl)
    pDARPP32_CaN = smodel.Spec('pDARPP32_CaN',mdl)
    DARPP32_C_actPKA = smodel.Spec('DARPP32_C_actPKA',mdl)
    
    
    
    pG_CaM3CaCaN = smodel.Spec('pG_CaM3CaCaN',mdl)
    act_PDE5 = smodel.Spec('act_PDE5',mdl)
    calc_3_1 = smodel.Spec('calc_3_1',mdl)
    calc_3_3 = smodel.Spec('calc_3_3',mdl)
    #calc_3_4 = smodel.Spec('calc_3_4',mdl)
    

    totbasGTP = smodel.Spec('totbasGTP',mdl)


    vsys = smodel.Volsys('vsys', mdl)
    
                                        

    ########################################################################
    ########################################################################
    
    #Reactions    
    #Ca influx (Ca = calcium)
    #CainfluxR = smodel.Reac('Cainflux', vsys, rhs=[Ca])
    #reaction constant for zero-order reaction units M/s in STEPS 1.2 and above
    #CainfluxR.kcst = 0.0 
    
    #CBf + Ca <-> CaCBf + Ca <-> Ca2CBf, CBf - medium affinity site
    #Reac27 = smodel.Reac('Reac27', vsys, lhs = [CBf, Ca], rhs = [CaCBf])
    #Reac27.kcst = 43.5e6 
    #Reac28 = smodel.Reac('Reac28', vsys, lhs = [CaCBf], rhs = [CBf, Ca])
    #Reac28.kcst = 35.8
    #Reac29 = smodel.Reac('Reac29', vsys, lhs = [CaCBf, Ca], rhs = [Ca2CBf])
    #Reac29.kcst = 43.5e6 
    #Reac30 = smodel.Reac('Reac30', vsys, lhs = [Ca2CBf], rhs = [CaCBf, Ca])
    #Reac30.kcst = 35.8

    # CaM + Ca <-> CaM1Ca <-> CaM2Ca <-> CaM3Ca 
    Reac208 = smodel.Reac('Reac208', vsys, lhs = [CaM, Ca], rhs = [CaM1Ca])
    Reac208.kcst = 4e6
    Reac209 = smodel.Reac('Reac209', vsys, lhs = [CaM1Ca], rhs = [CaM, Ca])
    Reac209.kcst = 100
    Reac210 = smodel.Reac('Reac210', vsys, lhs = [CaM1Ca,Ca], rhs = [CaM2Ca])
    Reac210.kcst = 40e6
    Reac211 = smodel.Reac('Reac211', vsys, lhs = [CaM2Ca], rhs = [CaM1Ca, Ca])
    Reac211.kcst = 640
    Reac212 = smodel.Reac('Reac212', vsys, lhs = [CaM2Ca, Ca], rhs = [CaM3Ca])
    Reac212.kcst = 40e6
    Reac213 = smodel.Reac('Reac213', vsys, lhs = [CaM3Ca], rhs = [CaM2Ca, Ca])
    Reac213.kcst = 700
    
    # CaN + CaM3Ca <-> CaM3CaCaN
    Reac214 = smodel.Reac('Reac214', vsys, lhs = [CaN, CaM3Ca] , rhs = [CaM3CaCaN])
    Reac214.kcst = 400e6
    Reac215 = smodel.Reac('Reac215', vsys, lhs = [CaM3CaCaN], rhs = [CaN,CaM3Ca])
    Reac215.kcst = 3 

    # CaMKII + CaM3Ca <-> CaM3Ca_CaMKII
    Reac216 = smodel.Reac('Reac216', vsys, lhs = [CaMKII, CaM3Ca], rhs = [CaM3Ca_CaMKII])
    Reac216.kcst = 400e6
    Reac217 = smodel.Reac('Reac217', vsys, lhs = [CaM3Ca_CaMKII], rhs = [CaMKII, CaM3Ca])
    Reac217.kcst = 8

    # CaM3Ca_CaMKII + calc_3_3 -> CaM3Ca_pT286287
    Reac218 = smodel.Reac('Reac218', vsys, lhs = [CaM3Ca_CaMKII,calc_3_3], rhs = [CaM3Ca_pT286287])
    Reac218.kcst = 11e6

    # CaM3Ca_pT286287 + PP1 <-> CaM3Ca_pT286287_PP1 -> CaM3Ca_CaMKII + PP1
    Reac219 = smodel.Reac('Reac219', vsys, lhs = [CaM3Ca_pT286287 , PP1], rhs = [CaM3Ca_pT286287_PP1])
    Reac219.kcst = 3.3333e6
    Reac220 = smodel.Reac('Reac220', vsys, lhs = [CaM3Ca_pT286287_PP1], rhs = [CaM3Ca_pT286287, PP1] )
    Reac220.kcst = 8
    Reac221 = smodel.Reac('Reac221', vsys, lhs = [CaM3Ca_pT286287_PP1], rhs = [CaM3Ca_CaMKII,PP1])
    Reac221.kcst = 2

    # CaM3Ca_pT286287 + PP2A <-> CaM3Ca_pT286287_PP2A -> CaM3Ca_CaMKII + PP2A
    Reac222 = smodel.Reac('Reac222', vsys, lhs = [CaM3Ca_pT286287 , PP2A], rhs = [CaM3Ca_pT286287_PP2A])
    Reac222.kcst = 0.2e6
    Reac223 = smodel.Reac('Reac223', vsys, lhs = [CaM3Ca_pT286287_PP2A], rhs = [CaM3Ca_pT286287, PP2A] )
    Reac223.kcst = 0.8
    Reac224 = smodel.Reac('Reac224', vsys, lhs = [CaM3Ca_pT286287_PP2A], rhs = [CaM3Ca_CaMKII, PP2A])
    Reac224.kcst = 0.2

    # pT286287 + CaM3Ca <-> CaM3Ca_pT286287
    Reac225 = smodel.Reac('Reac225', vsys, lhs = [pT286287, CaM3Ca], rhs = [CaM3Ca_pT286287])
    Reac225.kcst = 400e6
    Reac226 = smodel.Reac('Reac226', vsys, lhs = [CaM3Ca_pT286287], rhs = [pT286287, CaM3Ca])
    Reac226.kcst = 0.24

    # pT286287 -> pT286287_pT308306
    Reac227 = smodel.Reac('Reac227', vsys, lhs = [pT286287,calc_3_3], rhs = [pT286287_pT308306])
    Reac227.kcst = 0.5e6

    # pT286287_pT308306 + PP1 <-> pT286287_pT308306_PP1 -> pT286287 + PP1 
    Reac228 = smodel.Reac('Reac228', vsys, lhs = [pT286287_pT308306, PP1], rhs = [pT286287_pT308306_PP1])
    Reac228.kcst = 3.3333e6
    Reac229 = smodel.Reac('Reac229', vsys, lhs = [pT286287_pT308306_PP1], rhs =[pT286287_pT308306, PP1])
    Reac229.kcst = 8
    Reac230 = smodel.Reac('Reac230', vsys, lhs = [pT286287_pT308306_PP1], rhs = [pT286287, PP1])
    Reac230.kcst = 2

    # pT286287_pT308306 + PP2A <-> pT286287_pT308306_PP2A -> pT286287 + PP2A
    Reac231 = smodel.Reac('Reac231', vsys, lhs = [pT286287_pT308306, PP2A], rhs = [pT286287_pT308306_PP2A])
    Reac231.kcst = 0.2e6
    Reac232 = smodel.Reac('Reac232', vsys, lhs = [pT286287_pT308306_PP2A], rhs =[pT286287_pT308306, PP2A])
    Reac232.kcst = 0.8
    Reac233 = smodel.Reac('Reac233', vsys, lhs = [pT286287_pT308306_PP2A], rhs = [pT286287, PP2A])
    Reac233.kcst =  0.2

    # pT286287 + PP1 <-> pT286287_PP1 -> CaMKII + PP1
    Reac234 = smodel.Reac('Reac234', vsys, lhs = [pT286287, PP1], rhs = [pT286287_PP1])
    Reac234.kcst = 3.3333e6
    Reac235 = smodel.Reac('Reac235', vsys, lhs = [pT286287_PP1], rhs =[pT286287, PP1])
    Reac235.kcst = 8
    Reac236 = smodel.Reac('Reac236', vsys, lhs = [pT286287_PP1], rhs = [CaMKII, PP1])
    Reac236.kcst = 2

    # pT286287 + PP2A <-> pT286287_PP2A -> CaMKII + PP2A
    Reac237 = smodel.Reac('Reac237', vsys, lhs = [pT286287, PP2A], rhs = [pT286287_PP2A])
    Reac237.kcst = 0.2e6
    Reac238 = smodel.Reac('Reac238', vsys, lhs = [pT286287_PP2A], rhs =[pT286287, PP2A])
    Reac238.kcst = 0.8
    Reac239 = smodel.Reac('Reac239', vsys, lhs = [pT286287_PP2A], rhs = [CaMKII, PP2A])
    Reac239.kcst = 0.2

    # pT286287_pT308306 + PP1 <-> pT286287_pT308306_PP1_2 -> pT308306 + PP1
    Reac240 = smodel.Reac('Reac240', vsys, lhs = [pT286287_pT308306, PP1], rhs = [pT286287_pT308306_PP1_2])
    Reac240.kcst = 3.3333e6
    Reac241 = smodel.Reac('Reac241', vsys, lhs = [pT286287_pT308306_PP1_2], rhs =[pT286287_pT308306, PP1])
    Reac241.kcst = 8
    Reac242 = smodel.Reac('Reac242', vsys, lhs = [pT286287_pT308306_PP1_2], rhs = [pT308306, PP1])
    Reac242.kcst = 2

    # pT286287_pT308306 + PP2A <-> pT286287_pT308306_PP2A_2 -> pT308306 + PP2A
    Reac243 = smodel.Reac('Reac243', vsys, lhs = [pT286287_pT308306, PP2A], rhs = [pT286287_pT308306_PP2A_2])
    Reac243.kcst = 0.2e6
    Reac244 = smodel.Reac('Reac244', vsys, lhs = [pT286287_pT308306_PP2A_2], rhs =[pT286287_pT308306, PP2A])
    Reac244.kcst = 0.8
    Reac245 = smodel.Reac('Reac245', vsys, lhs = [pT286287_pT308306_PP2A_2], rhs = [pT308306, PP2A])
    Reac245.kcst = 0.2

 
    # pT308306 + PP1 <-> pT308306_PP1 -> CaMKII + PP1
    Reac246 = smodel.Reac('Reac246', vsys, lhs = [pT308306, PP1], rhs = [pT308306_PP1])
    Reac246.kcst = 3.3333e6
    Reac247 = smodel.Reac('Reac247', vsys, lhs = [pT308306_PP1], rhs =[pT308306, PP1])
    Reac247.kcst = 8
    Reac248 = smodel.Reac('Reac248', vsys, lhs = [pT308306_PP1], rhs = [CaMKII, PP1])
    Reac248.kcst = 2

    # pT308306 + PP2A <-> pT308306_PP2A -> CaMKII + PP2A
    Reac249 = smodel.Reac('Reac249', vsys, lhs = [pT308306, PP2A], rhs = [pT308306_PP2A])
    Reac249.kcst = 0.2e6
    Reac250 = smodel.Reac('Reac250', vsys, lhs = [pT308306_PP2A], rhs =[pT308306, PP2A])
    Reac250.kcst = 0.8
    Reac251 = smodel.Reac('Reac251', vsys, lhs = [pT308306_PP2A], rhs = [CaMKII, PP2A])
    Reac251.kcst = 0.2

    # GC + NO <-> GC_NO
    Reac252 = smodel.Reac('Reac252', vsys, lhs = [GC,NO], rhs = [GC_NO])
    Reac252.kcst = 1e6
    Reac253 = smodel.Reac('Reac253', vsys, lhs = [GC_NO], rhs = [GC,NO])
    Reac253.kcst = 0.01

    #GC_NO + GTP <-> GTP_GC_NO
    Reac254 = smodel.Reac('Reac254', vsys, lhs =[GC_NO, GTP], rhs = [GTP_GC_NO])
    Reac254.kcst = 0.735e6
    Reac255 = smodel.Reac('Reac255', vsys, lhs =[GTP_GC_NO], rhs = [GC_NO, GTP])
    Reac255.kcst = 29.4

    #GTP_GC_NO -> cGMP + GC_NO
    Reac256 = smodel.Reac('Reac256', vsys, lhs = [GTP_GC_NO], rhs = [cGMP,GC_NO])
    Reac256.kcst = 7.35

    #GC_NO -> GC
    Reac257 = smodel.Reac('Reac257', vsys, lhs = [GC_NO], rhs = [GC]) 
    Reac257.kcst = 0.673
    

    #cGMP + CaM3Ca_pPDE1 <-> cGMP_CaM3Ca_pPDE1 -> GMP + CaM3Ca_pPDE1
    Reac258 = smodel.Reac('Reac258', vsys, lhs = [cGMP,CaM3Ca_pPDE1], rhs = [cGMP_CaM3Ca_pPDE1])
    Reac258.kcst = 37.5e6
    Reac259 = smodel.Reac('Reac259', vsys, lhs = [cGMP_CaM3Ca_pPDE1], rhs = [cGMP,CaM3Ca_pPDE1])
    Reac259.kcst = 60
    Reac260 = smodel.Reac('Reac260', vsys, lhs = [cGMP_CaM3Ca_pPDE1], rhs = [GMP, CaM3Ca_pPDE1])
    Reac260.kcst = 15

    #cGMP + CaM3Ca_PDE1 <-> cGMP_CaM3Ca_PDE1 -> GMP + CaM3Ca_PDE1
    Reac261 = smodel.Reac('Reac261', vsys, lhs = [cGMP,CaM3Ca_PDE1], rhs = [cGMP_CaM3Ca_PDE1])
    Reac261.kcst = 37.5e6
    Reac262 = smodel.Reac('Reac262', vsys, lhs = [cGMP_CaM3Ca_PDE1], rhs = [cGMP,CaM3Ca_PDE1])
    Reac262.kcst = 60
    Reac263 = smodel.Reac('Reac263', vsys, lhs = [cGMP_CaM3Ca_PDE1], rhs = [GMP, CaM3Ca_PDE1])
    Reac263.kcst = 15 

    #cGMP + pPDE1 <-> cGMP_pPDE1 -> GMP + pPDE1
    Reac264 = smodel.Reac('Reac264', vsys, lhs = [cGMP,pPDE1], rhs = [cGMP_pPDE1])
    Reac264.kcst = 0.25e6
    Reac265 = smodel.Reac('Reac265', vsys, lhs = [cGMP_pPDE1], rhs = [cGMP,pPDE1])
    Reac265.kcst = 0.4 
    Reac266 = smodel.Reac('Reac266', vsys, lhs = [cGMP_pPDE1], rhs = [GMP, pPDE1])
    Reac266.kcst = 0.1

    #cGMP + PDE1 <-> cGMP_PDE1 -> GMP + PDE1 
    Reac267 = smodel.Reac('Reac267', vsys, lhs = [cGMP,PDE1], rhs = [cGMP_PDE1])
    Reac267.kcst = 0.25e6
    Reac268 = smodel.Reac('Reac268', vsys, lhs = [cGMP_PDE1], rhs = [cGMP,PDE1])
    Reac268.kcst = 0.4
    Reac269 = smodel.Reac('Reac269', vsys, lhs = [cGMP_PDE1], rhs = [GMP, PDE1])
    Reac269.kcst = 0.1

    #cGMP + PDE5 <-> cGMP_PDE5 -> GMP + PDE5 
    Reac270 = smodel.Reac('Reac270', vsys, lhs = [cGMP,act_PDE5], rhs = [cGMP_PDE5])
    Reac270.kcst = 7.5e6
    Reac271 = smodel.Reac('Reac271', vsys, lhs = [cGMP_PDE5], rhs = [cGMP,act_PDE5])
    Reac271.kcst = 12 
    Reac272 = smodel.Reac('Reac272', vsys, lhs = [cGMP_PDE5], rhs = [GMP, act_PDE5])
    Reac272.kcst = 3

    
    #pPDE1 -> PDE1 
    Reac273 = smodel.Reac('Reac273', vsys, lhs = [pPDE1], rhs = [PDE1])
    Reac273.kcst = 0.2

    #CaM3Ca_pPDE1 -> CaM3Ca_PDE1 
    Reac274 = smodel.Reac('Reac274', vsys, lhs = [CaM3Ca_pPDE1], rhs = [CaM3Ca_PDE1])
    Reac274.kcst = 0.2

    #PDE1  <-> PDE1_CaMKII -> pPDE1 
    Reac275 = smodel.Reac('Reac275', vsys, lhs = [PDE1,calc_3_1], rhs = [PDE1_CaMKII])
    Reac275.kcst = 0.90909090e6
    Reac276 = smodel.Reac('Reac276', vsys, lhs = [PDE1_CaMKII], rhs = [PDE1])
    Reac276.kcst = 8 
    Reac277 = smodel.Reac('Reac277', vsys, lhs = [PDE1_CaMKII], rhs = [pPDE1])
    Reac277.kcst = 2 

    #pPDE1 + CaN <-> pPDE1_CaN -> PDE1 + CaN
    Reac278 = smodel.Reac('Reac278', vsys, lhs = [pPDE1, CaM3CaCaN], rhs = [pPDE1_CaN])
    Reac278.kcst = 1.25e6
    Reac279 = smodel.Reac('Reac279', vsys, lhs = [pPDE1_CaN], rhs = [pPDE1, CaM3CaCaN])
    Reac279.kcst = 2 
    Reac280 = smodel.Reac('Reac280', vsys, lhs = [pPDE1_CaN], rhs = [PDE1, CaM3CaCaN])
    Reac280.kcst = 0.5 

    #CaM3Ca_PDE1 <-> CaM3Ca_PDE1_CaMKII -> CaM3Ca_pPDE1 
    Reac281 = smodel.Reac('Reac281', vsys, lhs = [CaM3Ca_PDE1,calc_3_1], rhs = [CaM3Ca_PDE1_CaMKII])
    Reac281.kcst = 0.90909090e6
    Reac282 = smodel.Reac('Reac282', vsys, lhs = [CaM3Ca_PDE1_CaMKII], rhs = [CaM3Ca_PDE1])
    Reac282.kcst = 8
    Reac283 = smodel.Reac('Reac283', vsys, lhs = [CaM3Ca_PDE1_CaMKII], rhs = [CaM3Ca_pPDE1])
    Reac283.kcst = 2

    #CaM3Ca_pPDE1 + CaN <-> CaM3Ca_pPDE1_CaN -> CaM3Ca_PDE1 + CaN
    Reac284 = smodel.Reac('Reac284', vsys, lhs = [CaM3Ca_pPDE1, CaM3CaCaN], rhs = [CaM3Ca_pPDE1_CaN])
    Reac284.kcst = 1.25e6
    Reac285 = smodel.Reac('Reac285', vsys, lhs = [CaM3Ca_pPDE1_CaN], rhs = [CaM3Ca_pPDE1, CaM3CaCaN])
    Reac285.kcst = 2 
    Reac286 = smodel.Reac('Reac286', vsys, lhs = [CaM3Ca_pPDE1_CaN], rhs = [CaM3Ca_PDE1, CaM3CaCaN])
    Reac286.kcst = 0.5


    #PDE1 + CaM3Ca <-> CaM3Ca_PDE1 
    Reac287 = smodel.Reac('Reac287', vsys, lhs = [PDE1,CaM3Ca], rhs = [CaM3Ca_PDE1])
    Reac287.kcst = 600e6
    Reac323 = smodel.Reac('Reac323', vsys, lhs = [CaM3Ca_PDE1], rhs = [PDE1,CaM3Ca])
    Reac323.kcst = 0.06 

    #pPDE1 + CaM3Ca <-> CaM3Ca_pPDE1 
    Reac288 = smodel.Reac('Reac288', vsys, lhs = [pPDE1,CaM3Ca], rhs = [CaM3Ca_pPDE1])
    Reac288.kcst = 600e6
    Reac324 = smodel.Reac('Reac324', vsys, lhs = [CaM3Ca_pPDE1], rhs = [pPDE1,CaM3Ca])
    Reac324.kcst = 0.36 

    #PP2A + pG <-> PP2A_pGsub
    Reac289 = smodel.Reac('Reac289', vsys, lhs = [PP2A,pG], rhs = [PP2A_pGsub])
    Reac289.kcst = 10e6
    Reac325 = smodel.Reac('Reac325', vsys, lhs = [PP2A_pGsub], rhs = [PP2A,pG])
    Reac325.kcst = 0.06

    #pG -> G_sub 
    Reac290 = smodel.Reac('Reac290', vsys, lhs = [pG], rhs = [G_sub])
    Reac290.kcst = 0.2

    #pG + PP2A <-> pG_PP2A -> G_sub + PP2A
    Reac291 = smodel.Reac('Reac291', vsys, lhs = [pG,PP2A], rhs = [pG_PP2A])
    Reac291.kcst = 2e6
    Reac292 = smodel.Reac('Reac292', vsys, lhs = [pG_PP2A], rhs = [pG,PP2A])
    Reac292.kcst = 8
    Reac293 = smodel.Reac('Reac293', vsys, lhs = [pG_PP2A], rhs = [G_sub, PP2A]) 
    Reac293.kcst = 2

    #pG + CaM3CaCaN <-> pG_CaM3CaCaN -> G_sub + CaM3CaCaN
    Reac294 = smodel.Reac('Reac294', vsys, lhs = [pG,CaM3CaCaN], rhs = [pG_CaM3CaCaN])
    Reac294.kcst = 1.5625e6
    Reac295 = smodel.Reac('Reac295', vsys, lhs = [pG_CaM3CaCaN], rhs = [pG,CaM3CaCaN])
    Reac295.kcst = 2
    Reac296 = smodel.Reac('Reac296', vsys, lhs = [pG_CaM3CaCaN], rhs = [G_sub, CaM3CaCaN]) 
    Reac296.kcst = 0.5 

    #G_sub + PKG_cGMP <-> G_sub_PKG -> pG + PKG
    Reac297 = smodel.Reac('Reac297', vsys, lhs = [G_sub,PKG_cGMP], rhs = [G_sub_PKG])
    Reac297.kcst = 50e6
    Reac298 = smodel.Reac('Reac298', vsys, lhs = [G_sub_PKG], rhs = [G_sub, PKG_cGMP])
    Reac298.kcst = 8
    Reac299 = smodel.Reac('Reac299', vsys, lhs = [G_sub_PKG], rhs = [pG, PKG_cGMP])
    Reac299.kcst = 2
    
    
    
    #PDE5 + cGMP + cGMP <-> act_PDE5
    Reac300 = smodel.Reac('Reac300', vsys, lhs= [PDE5,cGMP,cGMP], rhs = [act_PDE5])
    Reac300.kcst = 1e12
    Reac301 = smodel.Reac('Reac301', vsys, lhs = [act_PDE5], rhs = [PDE5, cGMP, cGMP])
    Reac301.kcst = 0.25 

    #PKG + cGMP + cGMP <-> PKG_cGMP
    Reac302 = smodel.Reac('Reac302', vsys, lhs= [PKG,cGMP,cGMP], rhs = [PKG_cGMP])
    Reac302.kcst = 2e12
    Reac303 = smodel.Reac('Reac303', vsys, lhs = [PKG_cGMP], rhs = [PKG, cGMP, cGMP])
    Reac303.kcst = 0.1

    #PP1_DARPP32 + C_actPKA <-> PP1_DARPP32_C_actPKA -> PP1_pDARPP32 + C_actPKA 
    Reac326 = smodel.Reac('Reac326', vsys, lhs = [PP1_DARPP32,C_actPKA], rhs = [PP1_DARPP32_C_actPKA])
    Reac326.kcst = 5.625e6
    Reac327 = smodel.Reac('Reac327', vsys, lhs = [PP1_DARPP32_C_actPKA], rhs = [PP1_DARPP32, C_actPKA])
    Reac327.kcst = 10.8
    Reac328 = smodel.Reac('Reac328', vsys, lhs = [PP1_DARPP32_C_actPKA], rhs = [PP1_pDARPP32,C_actPKA])
    Reac328.kcst = 2.7

    #PP1_pDARPP32 + CaM3CaCaN <-> PP1_pDARPP32_CaN -> PP1_DARPP32 + CaM3CaCaN 
    Reac329 = smodel.Reac('Reac329', vsys, lhs = [PP1_pDARPP32,CaM3CaCaN], rhs = [PP1_pDARPP32_CaN])
    Reac329.kcst = 1.5625e6
    Reac330 = smodel.Reac('Reac330', vsys, lhs = [PP1_pDARPP32_CaN], rhs = [PP1_pDARPP32, CaM3CaCaN])
    Reac330.kcst = 2.0
    Reac331 = smodel.Reac('Reac331', vsys, lhs = [PP1_pDARPP32_CaN], rhs = [PP1_DARPP32,CaM3CaCaN])
    Reac331.kcst = 0.5

    #PP1_pDARPP32 + PP2A <-> PP1_pDARPP32_PP2A -> PP1_DARPP32 + PP2A 
    Reac332 = smodel.Reac('Reac332', vsys, lhs = [PP1_pDARPP32,PP2A], rhs = [PP1_pDARPP32_PP2A])
    Reac332.kcst = 2e6
    Reac333 = smodel.Reac('Reac333', vsys, lhs = [PP1_pDARPP32_PP2A], rhs = [PP1_pDARPP32, PP2A])
    Reac333.kcst = 8.0
    Reac334 = smodel.Reac('Reac334', vsys, lhs = [PP1_pDARPP32_PP2A], rhs = [PP1_DARPP32,PP2A])
    Reac334.kcst = 2.0
    
    #DARPP32 + C_actPKA <-> DARPP32_C_actPKA -> pDARPP32 + C_actPKA 
    Reac335 = smodel.Reac('Reac335', vsys, lhs = [DARPP32,C_actPKA], rhs = [DARPP32_C_actPKA])
    Reac335.kcst = 5.625e6
    Reac336 = smodel.Reac('Reac336', vsys, lhs = [DARPP32_C_actPKA], rhs = [DARPP32, C_actPKA])
    Reac336.kcst = 10.8
    Reac337 = smodel.Reac('Reac337', vsys, lhs = [DARPP32_C_actPKA], rhs = [pDARPP32,C_actPKA])
    Reac337.kcst = 2.7

    #pDARPP32 + CaM3CaCaN <-> pDARPP32_CaN -> DARPP32 + CaM3CaCaN 
    Reac338 = smodel.Reac('Reac338', vsys, lhs = [pDARPP32,CaM3CaCaN], rhs = [pDARPP32_CaN])
    Reac338.kcst = 1.5625e6
    Reac339 = smodel.Reac('Reac339', vsys, lhs = [pDARPP32_CaN], rhs = [pDARPP32, CaM3CaCaN])
    Reac339.kcst = 2.0
    Reac340 = smodel.Reac('Reac340', vsys, lhs = [pDARPP32_CaN], rhs = [DARPP32,CaM3CaCaN])
    Reac340.kcst = 0.5

    #pDARPP32 + PP2A <-> pDARPP32_PP2A -> DARPP32 + PP2A 
    Reac341 = smodel.Reac('Reac341', vsys, lhs = [pDARPP32,PP2A], rhs = [pDARPP32_PP2A])
    Reac341.kcst = 2.0e6
    Reac342 = smodel.Reac('Reac342', vsys, lhs = [pDARPP32_PP2A], rhs = [pDARPP32,PP2A])
    Reac342.kcst = 8.0
    Reac343 = smodel.Reac('Reac343', vsys, lhs = [pDARPP32_PP2A], rhs = [DARPP32,PP2A])
    Reac343.kcst = 2.0
    
    #PP1 + DARPP32 <-> PP1_DARPP32 
    Reac344 = smodel.Reac('Reac344', vsys, lhs = [PP1, DARPP32], rhs = [ PP1_DARPP32])
    Reac344.kcst = 0.5e6
    Reac345 = smodel.Reac('Reac345', vsys, lhs = [PP1_DARPP32], rhs = [PP1, DARPP32])
    Reac345.kcst = 0.5

    #PP1 + pDARPP32 <-> PP1_pDARPP32 
    Reac346 = smodel.Reac('Reac346', vsys, lhs = [PP1, pDARPP32], rhs = [ PP1_pDARPP32])
    Reac346.kcst = 500e6
    Reac347 = smodel.Reac('Reac347', vsys, lhs = [PP1_pDARPP32], rhs = [PP1, pDARPP32])
    Reac347.kcst = 0.5   

    #R2C2_PKA + cAMP <-> cAMP_R2C2 
    Reac348 = smodel.Reac('Reac348', vsys, lhs = [R2C2_PKA,cAMP], rhs = [cAMP_R2C2])
    Reac348.kcst = 2e6
    Reac349 = smodel.Reac('Reac349', vsys, lhs = [cAMP_R2C2], rhs = [R2C2_PKA,cAMP])
    Reac349.kcst = 0.75

    #cAMP_R2C2 + cAMP <-> cAMP2_bb_R2C2 
    Reac350 = smodel.Reac('Reac350', vsys, lhs = [cAMP_R2C2,cAMP], rhs = [cAMP2_bb_R2C2])
    Reac350.kcst = 1e6
    Reac351 = smodel.Reac('Reac351', vsys, lhs = [cAMP2_bb_R2C2], rhs = [cAMP_R2C2,cAMP])
    Reac351.kcst = 1.5
    
    #cAMP_R2C2 + cAMP <-> cAMP2_ab_R2C2 
    Reac352 = smodel.Reac('Reac352', vsys, lhs = [cAMP_R2C2,cAMP], rhs = [cAMP2_ab_R2C2])
    Reac352.kcst = 10e6
    Reac353 = smodel.Reac('Reac353', vsys, lhs = [cAMP2_ab_R2C2], rhs = [cAMP_R2C2,cAMP])
    Reac353.kcst = 7.5
    
    #cAMP2_bb_R2C2 + cAMP <-> cAMP3_R2C2 
    Reac354 = smodel.Reac('Reac354', vsys, lhs = [cAMP2_bb_R2C2, cAMP], rhs = [cAMP3_R2C2])
    Reac354.kcst = 20e6
    Reac355 = smodel.Reac('Reac355', vsys, lhs = [cAMP3_R2C2], rhs = [cAMP2_bb_R2C2, cAMP])
    Reac355.kcst = 7.5 
    
    
    #cAMP2_ab_R2C2 + cAMP <-> cAMP3_R2C2 
    Reac356 = smodel.Reac('Reac356', vsys, lhs = [cAMP2_ab_R2C2, cAMP], rhs = [cAMP3_R2C2])
    Reac356.kcst = 1.0e6
    Reac357 = smodel.Reac('Reac357', vsys, lhs = [cAMP3_R2C2], rhs = [cAMP2_ab_R2C2, cAMP])
    Reac357.kcst = 0.75  

    #cAMP3_R2C2 + cAMP <-> cAMP4_R2C2 
    Reac358 = smodel.Reac('Reac358', vsys, lhs = [cAMP3_R2C2, cAMP], rhs = [cAMP4_R2C2])
    Reac358.kcst = 10e6
    Reac359 = smodel.Reac('Reac359', vsys, lhs = [cAMP4_R2C2], rhs = [cAMP3_R2C2,cAMP])
    Reac359.kcst = 15

    #cAMP2_ab_R2C2  <-> cAMP2_ab_R2C + C_actPKA
    Reac360 = smodel.Reac('Reac360', vsys, lhs = [cAMP2_ab_R2C2], rhs = [cAMP2_ab_R2C, C_actPKA])
    Reac360.kcst = 0.005
    Reac361 = smodel.Reac('Reac361', vsys, lhs = [cAMP2_ab_R2C, C_actPKA], rhs = [cAMP2_ab_R2C2])
    Reac361.kcst = 5e6

    #cAMP3_R2C2  <-> cAMP3_R2C + C_actPKA
    Reac362 = smodel.Reac('Reac362', vsys, lhs = [cAMP3_R2C2], rhs = [cAMP3_R2C, C_actPKA])
    Reac362.kcst = 0.005
    Reac363 = smodel.Reac('Reac363', vsys, lhs = [cAMP3_R2C, C_actPKA], rhs = [cAMP3_R2C2])
    Reac363.kcst = 5e6
    
    #cAMP4_R2C2  <-> cAMP4_R2C + C_actPKA
    Reac364 = smodel.Reac('Reac364', vsys, lhs = [cAMP4_R2C2], rhs = [cAMP4_R2C, C_actPKA])
    Reac364.kcst = 6
    Reac365 = smodel.Reac('Reac365', vsys, lhs = [cAMP4_R2C, C_actPKA], rhs = [cAMP4_R2C2])
    Reac365.kcst = 5e6
    
    #cAMP4_R2C  <-> cAMP4_R2 + C_actPKA
    Reac366 = smodel.Reac('Reac366', vsys, lhs = [cAMP4_R2C], rhs = [cAMP4_R2, C_actPKA])
    Reac366.kcst = 3
    Reac367 = smodel.Reac('Reac367', vsys, lhs = [cAMP4_R2, C_actPKA], rhs = [cAMP4_R2C])
    Reac367.kcst = 10e6

    #cAMP2_ab_R2C + cAMP <-> cAMP3_R2C  
    Reac368 = smodel.Reac('Reac368', vsys, lhs = [cAMP2_ab_R2C, cAMP], rhs = [cAMP3_R2C])
    Reac368.kcst = 1.0e6
    Reac369 = smodel.Reac('Reac369', vsys, lhs = [cAMP3_R2C], rhs = [cAMP2_ab_R2C, cAMP])
    Reac369.kcst =  0.75

    #cAMP3_R2C + cAMP <-> cAMP4_R2C 
    Reac370 = smodel.Reac('Reac370', vsys, lhs = [cAMP3_R2C, cAMP], rhs = [cAMP4_R2C])
    Reac370.kcst = 10e6
    Reac371 = smodel.Reac('Reac371', vsys, lhs = [cAMP4_R2C], rhs = [cAMP3_R2C,cAMP])
    Reac371.kcst = 7.5

    #cAMP + PDE4 <-> cAMP_PDE4 <-> AMP + PDE4
    Reac372 = smodel.Reac('Reac372',vsys, lhs = [cAMP,PDE4], rhs = [cAMP_PDE4])
    Reac372.kcst = 0.125e6
    Reac373 = smodel.Reac('Reac373',vsys, lhs = [cAMP_PDE4], rhs = [cAMP,PDE4])
    Reac373.kcst = 0.2
    Reac374 = smodel.Reac('Reac374',vsys, lhs = [cAMP_PDE4], rhs = [AMP,PDE4])
    Reac374.kcst = 0.05

    #cAMP + CaM3Ca_pPDE1 <-> cAMP_CaM3Ca_pPDE1 <-> AMP + CaM3Ca_pPDE1
    Reac375 = smodel.Reac('Reac375',vsys, lhs = [cAMP,CaM3Ca_pPDE1], rhs = [cAMP_CaM3Ca_pPDE1])
    Reac375.kcst = 2.0833e6
    Reac376 = smodel.Reac('Reac376',vsys, lhs = [cAMP_CaM3Ca_pPDE1], rhs = [cAMP,CaM3Ca_pPDE1])
    Reac376.kcst = 20
    Reac377 = smodel.Reac('Reac377',vsys, lhs = [cAMP_CaM3Ca_pPDE1], rhs = [AMP,CaM3Ca_pPDE1])
    Reac377.kcst = 5

    #cAMP + CaM3Ca_PDE1 <-> cAMP_CaM3Ca_PDE1 <-> AMP + CaM3Ca_PDE1
    Reac378 = smodel.Reac('Reac378',vsys, lhs = [cAMP,CaM3Ca_PDE1], rhs = [cAMP_CaM3Ca_PDE1])
    Reac378.kcst = 2.0833e6
    Reac379 = smodel.Reac('Reac379',vsys, lhs = [cAMP_CaM3Ca_PDE1], rhs = [cAMP,CaM3Ca_PDE1])
    Reac379.kcst = 20
    Reac380 = smodel.Reac('Reac380',vsys, lhs = [cAMP_CaM3Ca_PDE1], rhs = [AMP,CaM3Ca_PDE1])
    Reac380.kcst = 5

    #cAMP + pPDE1 <-> cAMP_pPDE1 <-> AMP + pPDE1
    Reac381 = smodel.Reac('Reac381',vsys, lhs = [cAMP,pPDE1], rhs = [cAMP_pPDE1])
    Reac381.kcst = 0.0416e6
    Reac382 = smodel.Reac('Reac382',vsys, lhs = [cAMP_pPDE1], rhs = [cAMP,pPDE1])
    Reac382.kcst = 0.4
    Reac383 = smodel.Reac('Reac383',vsys, lhs = [cAMP_pPDE1], rhs = [AMP,pPDE1])
    Reac383.kcst = 0.1

    #cAMP + PDE1 <-> cAMP_PDE1 <-> AMP + PDE1
    Reac384 = smodel.Reac('Reac384',vsys, lhs = [cAMP,PDE1], rhs = [cAMP_PDE1])
    Reac384.kcst = 0.0416e6
    Reac385 = smodel.Reac('Reac385',vsys, lhs = [cAMP_PDE1], rhs = [cAMP,PDE1])
    Reac385.kcst = 0.4
    Reac386 = smodel.Reac('Reac386',vsys, lhs = [cAMP_PDE1], rhs = [AMP,PDE1])
    Reac386.kcst = 0.1

    



    return mdl

########################################################################

# Geometric properties of the model: To change the size of the model, all volumetric compartments must be altered by the same ratio
# and all the areas must be scaled considering a spherical shape.
# Alterations in the size of the compartments will change automatically the population
# of species given in concentration (initial condition), but the species given in number of molecules must be altered manually by the same ratio
# to keep the balance among all the components of the model. 

def gen_geom():    
    g = swm.Geom()
    c = swm.Comp('vsys', g)
    c.addVolsys('vsys')
    c.vol = 2.2e-18
    
    
    return g

######################################################################


rng=srng.create('mt19937',512)
m=gen_model() 
g=gen_geom() 
tpnts=np.arange(0.0,INT,DT)
ntpnts=tpnts.shape[0]
    
# initialize arrays for storage at each time point and at each run.
Ca = numpy.zeros((NITER, ntpnts))
#CBf = numpy.zeros((NITER, ntpnts))
#CaCBf = numpy.zeros((NITER, ntpnts))
#Ca2CBf = numpy.zeros((NITER, ntpnts))
PP2A = numpy.zeros((NITER, ntpnts))
PP1 = numpy.zeros((NITER, ntpnts)) 
   
CaM = numpy.zeros((NITER, ntpnts))
CaM1Ca = numpy.zeros((NITER, ntpnts))
CaM2Ca = numpy.zeros((NITER, ntpnts))
CaM3Ca = numpy.zeros((NITER, ntpnts))
CaN = numpy.zeros((NITER, ntpnts))
CaMKII = numpy.zeros((NITER, ntpnts))
CaM3Ca_CaMKII = numpy.zeros((NITER, ntpnts))
CaM3Ca_pT286287 = numpy.zeros((NITER, ntpnts))
pT286287 = numpy.zeros((NITER, ntpnts))
pT286287_pT308306 = numpy.zeros((NITER, ntpnts))
pT308306 = numpy.zeros((NITER, ntpnts))

GC = numpy.zeros((NITER, ntpnts))
NO = numpy.zeros((NITER, ntpnts))
GC_NO = numpy.zeros((NITER, ntpnts))
GTP = numpy.zeros((NITER, ntpnts))
GTP_GC_NO = numpy.zeros((NITER, ntpnts))
cGMP = numpy.zeros((NITER, ntpnts))
GMP = numpy.zeros((NITER,ntpnts))
PDE1 = numpy.zeros((NITER, ntpnts))
pPDE1 = numpy.zeros((NITER, ntpnts))
PDE5 = numpy.zeros((NITER, ntpnts))
PDE5_cGMP = numpy.zeros((NITER, ntpnts))
PKG = numpy.zeros((NITER, ntpnts))
PKG_cGMP = numpy.zeros((NITER, ntpnts))
CaM3Ca_PDE1 = numpy.zeros((NITER, ntpnts))
CaM3Ca_pPDE1 = numpy.zeros((NITER, ntpnts))
GMP = numpy.zeros((NITER, ntpnts))
PP2A_pGsub = numpy.zeros((NITER, ntpnts))
pG = numpy.zeros((NITER, ntpnts))
G_sub = numpy.zeros((NITER, ntpnts))

CaM3Ca_pT286287_PP1 = numpy.zeros((NITER, ntpnts))
CaM3Ca_pT286287_PP2A = numpy.zeros((NITER, ntpnts))
pT286287_pT308306_PP1 = numpy.zeros((NITER, ntpnts))
pT286287_pT308306_PP2A = numpy.zeros((NITER, ntpnts))
pT286287_PP1 = numpy.zeros((NITER, ntpnts))
pT286287_PP2A = numpy.zeros((NITER, ntpnts))
pT286287_pT308306_PP1_2 = numpy.zeros((NITER, ntpnts))
pT286287_pT308306_PP2A_2 = numpy.zeros((NITER, ntpnts))
pT308306_PP1 = numpy.zeros((NITER, ntpnts))
pT308306_PP2A = numpy.zeros((NITER, ntpnts))
cGMP_CaM3Ca_pPDE1 = numpy.zeros((NITER, ntpnts))
cGMP_CaM3Ca_PDE1 = numpy.zeros((NITER, ntpnts))
cGMP_PDE1 = numpy.zeros((NITER, ntpnts))
cGMP_pPDE1 = numpy.zeros((NITER, ntpnts))
PDE1_CaMKII = numpy.zeros((NITER, ntpnts))
pPDE1_CaN = numpy.zeros((NITER, ntpnts))    
CaM3Ca_PDE1_CaMKII = numpy.zeros((NITER, ntpnts))
CaM3Ca_pPDE1_CaN = numpy.zeros((NITER, ntpnts))
pG_PP2A = numpy.zeros((NITER, ntpnts))
pG_CaN = numpy.zeros((NITER, ntpnts))
G_sub_PKG = numpy.zeros((NITER, ntpnts))
pDARPP32_PP2A = numpy.zeros((NITER, ntpnts))
PP1_pDARPP32 = numpy.zeros((NITER, ntpnts))
PP1_DARPP32 = numpy.zeros((NITER, ntpnts))
DARPP32 = numpy.zeros((NITER, ntpnts))
pDARPP32 = numpy.zeros((NITER, ntpnts))
R2C2_PKA = numpy.zeros((NITER, ntpnts))
cAMP_R2C2 = numpy.zeros((NITER, ntpnts))
cAMP2_bb_R2C2 = numpy.zeros((NITER, ntpnts))
cAMP2_ab_R2C2 = numpy.zeros((NITER, ntpnts))
cAMP2_ab_R2C = numpy.zeros((NITER, ntpnts))
cAMP3_R2C2 = numpy.zeros((NITER, ntpnts))
cAMP3_R2C = numpy.zeros((NITER, ntpnts))
cAMP4_R2C2 = numpy.zeros((NITER, ntpnts))
cAMP4_R2C = numpy.zeros((NITER, ntpnts))
cAMP4_R2 = numpy.zeros((NITER, ntpnts))
C_actPKA = numpy.zeros((NITER, ntpnts))
cAMP = numpy.zeros((NITER, ntpnts))
AMP = numpy.zeros((NITER, ntpnts))
PDE4 = numpy.zeros((NITER, ntpnts))
cAMP_PDE4 = numpy.zeros((NITER, ntpnts)) 
cAMP_PDE1 = numpy.zeros((NITER, ntpnts))
cAMP_pPDE1 = numpy.zeros((NITER, ntpnts))
cAMP_CaM3Ca_PDE1 = numpy.zeros((NITER, ntpnts))
cAMP_CaM3Ca_pPDE1  = numpy.zeros((NITER, ntpnts))
PP1_pDARPP32_PP2A  = numpy.zeros((NITER, ntpnts))
calc_3_1 = numpy.zeros((NITER, ntpnts))


pG_CaM3CaCaN = numpy.zeros((NITER, ntpnts))
totPKC = numpy.zeros((NITER, ntpnts))
actCaMKII = numpy.zeros((NITER, ntpnts))
GMP = numpy.zeros((NITER, ntpnts))
pPDE1 = numpy.zeros((NITER, ntpnts))
act_PDE5 = numpy.zeros((NITER, ntpnts))

#ica=gaussian_ica(tpnts)
    
sim = swmdirect.Wmdirect(m, g, rng)
    
    
for j in arange(NITER): 
    print "Run number {0}".format(j)
    rng.initialize(datetime.datetime.now().microsecond) 
    sim.reset() 
    
    
    sim.setCompConc('vsys','NO',0.05e-6)
    sim.setCompClamped('vsys','NO',True)

    sim.setCompConc('vsys','CaMKII',Kin*1e-6)
    sim.setCompConc('vsys','CaM',60e-6)
    sim.setCompConc('vsys','CaN',10e-6)
    
    
    
    sim.setCompConc('vsys','DARPP32',0.7e-6)
    sim.setCompConc('vsys','R2C2_PKA',0.25e-6)
    
    
    sim.setCompConc('vsys','PP2A',0.4e-6)
    sim.setCompConc('vsys','PP1',0.4e-6)
    sim.setCompConc('vsys','PDE5',0.6e-6)
    sim.setCompConc('vsys','PDE1',0.6e-6)
    sim.setCompConc('vsys','PDE4',0.6e-6)
    sim.setCompConc('vsys','GC',0.02e-6)

    sim.setCompConc('vsys','PKG',0.1e-6)
    
    sim.setCompConc('vsys','G_sub',0.7e-6)
 
    sim.setCompConc('vsys','cAMP', 0.15e-6)

    sim.setCompConc('vsys','AMP',1000e-6)
    sim.setCompClamped('vsys','AMP',True)

    sim.setCompConc('vsys','GTP',100e-6)
    sim.setCompClamped('vsys','GTP',True)
    sim.setCompConc('vsys','GMP', 0.1e-6)
    sim.setCompClamped('vsys','GMP',True)
    sim.setCompConc('vsys','cGMP', 0.02e-6)

   
    






    for i in range(ntpnts):
        if (tpnts[i] < 1000) : sim.setCompConc('vsys','Ca',0.1e-6)
        if ((tpnts[i] > 1000) and (tpnts[i] < 1030)): sim.setCompConc('vsys','Ca',2e-6)
        #if ((tpnts[i] > 600) and (tpnts[i] < 605)): sim.setCompConc('vsys','Ca',0.1e-6)
        #if ((tpnts[i] > 605) and (tpnts[i] < 620)): sim.setCompConc('vsys','Ca',0.8e-6)
        #if ((tpnts[i] > 520) and (tpnts[i] < 623)): sim.setCompConc('vsys','Ca',0.1e-6)
        #if ((tpnts[i] > 523) and (tpnts[i] < 630)): sim.setCompConc('vsys','Ca',0.8e-6)
        #if ((tpnts[i] > 560) and (tpnts[i] < 631)): sim.setCompConc('vsys','Ca',0.8e-6)
        #if ((tpnts[i] > 900) and (tpnts[i] < 1200)): sim.setCompConc('vsys','Ca',1.5e-6)
        #if ((tpnts[i] > 900) and (tpnts[i] < 1200)): sim.setCompConc('vsys','Ca',1.5e-6)
        #if ((tpnts[i] > 900) and (tpnts[i] < 1200)): sim.setCompConc('vsys','Ca',1.5e-6)
        if (tpnts[i] > 1030) : sim.setCompConc('vsys','Ca',0.1e-6)
        sim.setCompConc('vsys','calc_3_1', sim.getCompConc('vsys','CaM3Ca_pT286287') + sim.getCompConc('vsys','pT286287') + sim.getCompConc('vsys','CaM3Ca_CaMKII') + sim.getCompConc('vsys','pT286287_pT308306'))
        #calc_3_1 =  sim.getCompConc('vsys','CaM3Ca_pT286287') + sim.getCompConc('vsys','pT286287') + sim.getCompConc('vsys','CaM3Ca_CaMKII') + sim.getCompConc('vsys','pT286287_pT308306')
        #a = sim.getCompConc('vsys','calc_3_1')
        calc_3_4 =  sim.getCompConc('vsys','calc_3_1') + sim.getCompConc('vsys','CaMKII') + sim.getCompConc('vsys','pT308306') + sim.getCompConc('vsys','pT308306_PP1') + sim.getCompConc('vsys','pT286287_PP1') + sim.getCompConc('vsys','pT286287_pT308306_PP2A_2') + sim.getCompConc('vsys','pT286287_pT308306_PP2A') + sim.getCompConc('vsys','CaM3Ca_pT286287_PP1') + sim.getCompConc('vsys','CaM3Ca_pT286287_PP2A') + sim.getCompConc('vsys','pT286287_PP2A') + sim.getCompConc('vsys','pT286287_pT308306_PP1') + sim.getCompConc('vsys','pT286287_pT308306_PP1_2') + sim.getCompConc('vsys','pT308306_PP2A')
        sim.setCompConc('vsys','calc_3_3', sim.getCompConc('vsys','calc_3_1')/calc_3_4)
        #calc_3_4 =  calc_3_1 + sim.getCompConc('vsys','CaMKII') + sim.getCompConc('vsys','pT308306') + sim.getCompConc('vsys','pT308306_PP1') + sim.getCompConc('vsys','pT286287_PP1') + sim.getCompConc('vsys','pT286287_pT308306_PP2A_2') + sim.getCompConc('vsys','pT286287_pT308306_PP2A') + sim.getCompConc('vsys','CaM3Ca_pT286287_PP1') + sim.getCompConc('vsys','CaM3Ca_pT286287_PP2A') + sim.getCompConc('vsys','pT286287_PP2A') + sim.getCompConc('vsys','pT286287_pT308306_PP1') + sim.getCompConc('vsys','pT286287_pT308306_PP1_2') + sim.getCompConc('vsys','pT308306_PP2A')
        
        #sim.setCompConc('vsys','calc_3_3', calc_3_1/calc_3_4)

        #calc_3_3 =  sim.getCompConc('vsys','calc_3_1')/calc_3_4
        #calc_3_3 =  calc_3_1/calc_3_4


        sim.run(tpnts[i]) 

        print "percent done",(tpnts[i]/INT*100),j 
        #a = sim.getCompCount('vsys','PP2A') 
        #b = sim.getCompCount('vsys','PKC_AA')
        #print   calc_3_3
            

        Ca[j,i] = sim.getCompConc('vsys','Ca')
        #CaCBf[j,i] = sim.getCompConc('vsys', 'CaCBf')
        #Ca2CBf[j,i] = sim.getCompConc('vsys', 'Ca2CBf')
        CaMKII[j,i] = sim.getCompConc('vsys','CaMKII')
        CaM1Ca[j,i] = sim.getCompConc('vsys','CaM1Ca')
        CaM2Ca[j,i] = sim.getCompConc('vsys','CaM2Ca')
        CaM3Ca[j,i] = sim.getCompConc('vsys','CaM3Ca')
        PDE1[j,i] = sim.getCompConc('vsys','PDE1')
        pG[j,i] = sim.getCompConc('vsys','pG')    
        CaM3Ca_pT286287[j,i] = sim.getCompConc('vsys', 'CaM3Ca_pT286287')
        PP2A[j,i] = sim.getCompConc('vsys', 'PP2A')
        PP2A_pGsub[j,i] = sim.getCompConc('vsys','PP2A_pGsub')
        pT286287_PP2A[j,i] = sim.getCompConc('vsys','pT286287_PP2A')    
        pT308306_PP2A[j,i] = sim.getCompConc('vsys','pT308306_PP2A')
        pDARPP32_PP2A[j,i] = sim.getCompConc('vsys','pDARPP32_PP2A')
        pG_PP2A[j,i] = sim.getCompConc('vsys','pG_PP2A')
        PP1_pDARPP32_PP2A[j,i] = sim.getCompConc('vsys','PP1_pDARPP32_PP2A')
        pT286287_pT308306_PP2A[j,i] = sim.getCompConc('vsys','pT286287_pT308306_PP2A')
        CaM3Ca_pT286287_PP2A[j,i] = sim.getCompConc('vsys','CaM3Ca_pT286287_PP2A')
        pT286287_pT308306_PP2A_2[j,i] = sim.getCompConc('vsys','pT286287_pT308306_PP2A_2')
        C_actPKA[j,i] = sim.getCompConc('vsys','C_actPKA')
        PDE1[j,i] = sim.getCompConc('vsys','PDE1')  
        pPDE1[j,i] = sim.getCompConc('vsys','pPDE1')    
        cAMP_PDE1[j,i] = sim.getCompConc('vsys','cAMP_PDE1')
        cGMP_PDE1[j,i] = sim.getCompConc('vsys','cGMP_PDE1')
        CaM3Ca_PDE1[j,i] = sim.getCompConc('vsys','CaM3Ca_PDE1')
        CaM3Ca_pPDE1[j,i] = sim.getCompConc('vsys','CaM3Ca_pPDE1')
        cAMP_CaM3Ca_pPDE1[j,i] = sim.getCompConc('vsys','cAMP_CaM3Ca_pPDE1')
        cAMP_CaM3Ca_PDE1[j,i] = sim.getCompConc('vsys','cAMP_CaM3Ca_PDE1')   
        CaM3Ca_pPDE1[j,i] = sim.getCompConc('vsys','CaM3Ca_pPDE1')
        CaM3Ca[j,i] = sim.getCompConc('vsys','CaM3Ca')
        cAMP[j,i] = sim.getCompConc('vsys','cAMP')
        cGMP[j,i] = sim.getCompConc('vsys','cGMP')
        PKG[j,i] = sim.getCompConc('vsys','PKG')
        pDARPP32[j,i] = sim.getCompConc('vsys','pDARPP32')
        DARPP32[j,i] = sim.getCompConc('vsys','DARPP32')
        PP1_pDARPP32[j,i] = sim.getCompConc('vsys','PP1_pDARPP32')
        PP1_DARPP32[j,i] = sim.getCompConc('vsys','PP1_DARPP32')
        CaN[j,i] = sim.getCompConc('vsys','CaN')
        PP1[j,i] = sim.getCompConc('vsys','PP1')
        #totPKC[j,i] = sim.getCompCount('vsys','totPKC')
        C_actPKA[j,i] = sim.getCompConc('vsys','C_actPKA')
        PDE4[j,i] = sim.getCompConc('vsys','PDE4')
       
        PP1_DARPP32[j,i] = sim.getCompConc('vsys','PP1_DARPP32')
        G_sub[j,i] = sim.getCompConc('vsys','G_sub')
        CaN[j,i] = sim.getCompConc('vsys','CaN')
        PKG[j,i] = sim.getCompConc('vsys','PKG')
        cAMP_R2C2[j,i] = sim.getCompConc('vsys','cAMP_R2C2')
        cAMP4_R2C2[j,i] = sim.getCompConc('vsys','cAMP4_R2C2')
        
        NO[j,i] = sim.getCompConc('vsys','NO')
        GC[j,i] = sim.getCompConc('vsys','GC')
        GC_NO[j,i] = sim.getCompConc('vsys','GC_NO')
        R2C2_PKA[j,i] = sim.getCompConc('vsys','R2C2_PKA')
        
         
        CaMKII[j,i] = sim.getCompConc('vsys','CaMKII')
        CaM3Ca_CaMKII[j,i] = sim.getCompConc('vsys','CaM3Ca_CaMKII')
        CaM3Ca_pT286287[j,i] = sim.getCompConc('vsys','CaM3Ca_pT286287')
        pT286287[j,i] = sim.getCompConc('vsys','pT286287')
        pT308306[j,i] = sim.getCompConc('vsys','pT308306')
        PDE4[j,i] = sim.getCompConc('vsys','PDE4')
        PDE5[j,i] = sim.getCompConc('vsys','PDE5')
        act_PDE5[j,i] = sim.getCompConc('vsys','act_PDE5')
        #PDE1_CaMKII[j,i] = sim.getCompConc('vsys','PDE1_CaMKII')
        #CaM3Ca_PDE1_CaMKII[j,i] = sim.getCompConc('vsys','CaM3Ca_PDE1_CaMKII')
        calc_3_1[j,i] = sim.getCompConc('vsys','calc_3_1')

        #sim.setCompReacK('vsys', 'Cainflux', ica[i]) # changes reaction constant to be ...

PP2A_mean = mean(PP2A, axis = 0)
plot(linspace(0,INT,INT/DT), PP2A_mean, 'y')
xlabel('Time (s)')
ylabel('PP2A (#)')
savefig('PP2A.png')
close()    
        
PP1_mean = mean(PP1, axis = 0)
plot(linspace(0,INT,INT/DT), PP1_mean, 'y')
xlabel('Time (s)')
ylabel('PP1 (#)')
savefig('PP1.png')
close()    

cAMP_mean = mean(cAMP, axis = 0)
plot(linspace(0,INT,INT/DT), cAMP_mean, 'y')
xlabel('Time (s)')
ylabel('cAMP (#)')
savefig('cAMP.png')
close() 

cGMP_mean = mean(cGMP, axis = 0)
plot(linspace(0,INT,INT/DT), cGMP_mean, 'y')
xlabel('Time (s)')
ylabel('cGMP (#)')
savefig('cGMP.png')
close() 

PDE1_mean = mean(PDE1, axis = 0)
plot(linspace(0,INT,INT/DT), PDE1_mean, 'y')
xlabel('Time (s)')
ylabel('PDE1 (#)')
savefig('PDE1.png')
close() 

PDE5_mean = mean(PDE5, axis = 0)
plot(linspace(0,INT,INT/DT), PDE5_mean, 'y')
xlabel('Time (s)')
ylabel('PDE5 (#)')
savefig('PDE5.png')
close() 

pPDE1_mean = mean(pPDE1, axis = 0)
plot(linspace(0,INT,INT/DT), pPDE1_mean, 'y')
xlabel('Time (s)')
ylabel('pPDE1 (#)')
savefig('pPDE1.png')
close() 

CaMKII_mean = mean(CaMKII, axis = 0)
plot(linspace(0,INT,INT/DT), CaMKII_mean, 'y')
xlabel('Time (s)')
ylabel('CaMKII (#)')
savefig('CaMKII.png')
close() 

PKG_mean = mean(PKG, axis = 0)
plot(linspace(0,INT,INT/DT), PKG_mean, 'y')
xlabel('Time (s)')
ylabel('PKG (#)')
savefig('PKG.png')
close() 

pG_mean = mean(pG, axis = 0)
plot(linspace(0,INT,INT/DT), pG_mean, 'y')
xlabel('Time (s)')
ylabel('pG (#)')
savefig('pG.png')
close() 

PKA_mean = mean(C_actPKA, axis = 0)
plot(linspace(0,INT,INT/DT), PKA_mean, 'y')
xlabel('Time (s)')
ylabel('PKA (#)')
savefig('PKA.png')
close() 

DARPP32_mean = mean(DARPP32, axis = 0)
plot(linspace(0,INT,INT/DT), DARPP32_mean, 'y')
xlabel('Time (s)')
ylabel('DARPP32 (#)')
savefig('DARPP32_mean.png')
close() 




CaM3Ca_PDE1_mean = mean(CaM3Ca_PDE1, axis = 0)
plot(linspace(0,INT,INT/DT), CaM3Ca_PDE1_mean, 'y')
xlabel('Time (s)')
ylabel('CaM3Ca_PDE1(#)')
savefig('CaM3Ca_PDE1_mean.png')
close() 

CaM3Ca_pPDE1_mean = mean(CaM3Ca_pPDE1, axis = 0)
plot(linspace(0,INT,INT/DT), CaM3Ca_pPDE1_mean, 'y')
xlabel('Time (s)')
ylabel('CaM3Ca_pPDE1(#)')
savefig('CaM3Ca_pPDE1_mean.png')
close() 

calc_3_1_mean = mean(calc_3_1, axis = 0)
plot(linspace(0,INT,INT/DT), calc_3_1_mean, 'y')
xlabel('Time (s)')
ylabel('calc_3_1(#)')
savefig('actCaMKII.png')
close() 

#CaM3Ca_PDE1_CaMKII_mean = mean(CaM3Ca_PDE1_CaMKII, axis = 0)
#plot(linspace(0,INT,INT/DT), CaM3Ca_PDE1_CaMKII_mean, 'y')
#xlabel('Time (s)')
#ylabel('CaM3Ca_PDE1_CaMKII(#)')
#savefig('CaM3Ca_PDE1_CaMKII_mean.png')
#close() 

#PDE1_CaMKII_mean = mean(PDE1_CaMKII, axis = 0)
#plot(linspace(0,INT,INT/DT), PDE1_CaMKII_mean, 'y')
#xlabel('Time (s)')
#ylabel('PDE1_CaMKII(#)')
#savefig('PDE1_CaMKII_mean.png')
#close()

CaM3Ca_CaMKII_mean = mean(CaM3Ca_CaMKII, axis = 0)
plot(linspace(0,INT,INT/DT), CaM3Ca_CaMKII_mean, 'y')
xlabel('Time (s)')
ylabel('CaM3Ca_CaMKII(#)')
savefig('CaM3Ca_CaMKII.png')
close()  

CaM3Ca_pT286287_mean = mean(CaM3Ca_pT286287, axis = 0)
plot(linspace(0,INT,INT/DT), CaM3Ca_pT286287_mean, 'y')
xlabel('Time (s)')
ylabel('CaM3Ca_pT286287(#)')
savefig('CaM3Ca_pT286287.png')
close()  

pT286287_mean = mean(pT286287, axis = 0)
plot(linspace(0,INT,INT/DT), pT286287_mean, 'y')
xlabel('Time (s)')
ylabel('pT286287(#)')
savefig('pT286287.png')
close() 

pT308306_mean = mean(pT308306, axis = 0)
plot(linspace(0,INT,INT/DT), pT308306_mean, 'y')
xlabel('Time (s)')
ylabel('pT308306(#)')
savefig('pT308306.png')
close()  

CaM3Ca_mean = mean(CaM3Ca, axis = 0)
plot(linspace(0,INT,INT/DT), CaM3Ca_mean, 'y')
xlabel('Time (s)')
ylabel('CaM3Ca(#)')
savefig('CaM3Ca.png')
close()  

CaN_mean = mean(CaN, axis = 0)
plot(linspace(0,INT,INT/DT), CaN_mean, 'y')
xlabel('Time (s)')
ylabel('CaN(#)')
savefig('CaN.png')
close() 

